bf2fc6cc711aee1a0c2a/kas-fleet-manager

CONTRIBUTING.md
docs/adding-a-new-config-module.md
docs/adding-new-flags.md

We should have documentation on how to add Config Modules, adding new config files in [internal/kafka/internal/config](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/tree/main/internal/kafka/internal/config), so that anyone who needs this will have a reference on what changes they need to make and where to place this new configuration.
Jira: https://issues.redhat.com/browse/MGDSTRM-7659
1. Go to /docs.
2. The new file is adding-a-new-ConfigModule.md
3. Also added a link in CONTRIBUTING.md

docs: Added documentation on how to add a new ConfigModule

---

internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go

Remove check if KasFleetshardOperatorAddon is set, as KasFleetshardOperator will always be set. Also remove the test for this.
[MGDSTRM-7889](https://issues.redhat.com/browse/MGDSTRM-7889)

refactor: Remove check for KasFleetshardOperatorAddon

---

internal/kafka/internal/config/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/quota/quota_management_list_service_test.go

This was removed in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/824 and should not be added back into main.
- CI checks passing

fix: remove unused MaxCapacity in KafkaConfig

---

pkg/server/healthcheck_config.go
pkg/server/metrics_config.go
pkg/server/server_config.go
templates/service-template.yml

Removed spelling error in log message for BindAddress flag.
Adddress -> Address

style: remove spelling error in server_config.go

---

.github/workflows/ci.yaml
Dockerfile
README.md
docker/Dockerfile_template
docker/Dockerfile_template_mocked
go.mod

Update to Go 1.17.
Reason: It was already updated for the building of the kas fleet manager container image. This PR makes it consistent in the other places where Go is being used. Additionally, for the kas fleet manager container image the Go version has been updated to 1.17.8 to fix CVE-2022-23773. 
It has been done in:
- GitHub Actions
- docker/Dockerfile_template
- docker/Dockerfile_template_mocked
Additionally:
- Update go.mod to 1.17 and rebuild it with go mod tiny
- Update minimum Go version to 1.17.x in README
- Update GitHub workflow module actions/setup-go to v3
- Update to Go 1.17.8 in main Dockerfile by manually downloading
it using ubi8 minimal as the base image to fix CVE CVE-2022-23773. The reason on doing it in this way
is due to at the moment of writing this the Go …

feat: Update Go to 1.17

---

docs/deploying-kas-fleet-manager-to-openshift.md

Added the following guides to the Deploying KAS Fleet Manager to OpenShift documentation:
* How to build and push KAS Fleet Manager image to your own external registry
* How to use a private image registry when deploying KAS Fleet Manager on OpenShift
1. Run through the documentation and ensure all commands works as expected.
- Build and push the KAS Fleet Manager image to a private external registry instead of pushing it to the OpenShift internal registry.

docs: add guide for using an external image repository

---

internal/connector/internal/workers/connector_mgr.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_routes_cname_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_routes_cname_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/preparing_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/preparing_kafkas_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/ready_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/ready_kafkas_mgr_test.go
internal/kafka/test/integration/kafkas_test.go
pkg/providers/core.go
pkg/workers/leader_election_mgr.go
pkg/workers/leader_election_mgr_test.go
pkg/workers/reconciler.go
pkg/workers/reconciler_config.go
pkg/workers/reconciler_test.go
templates/service-template.yml
test/helper.go

Make reconciler interval, leader lease expiration time and repeat interval configurable so that they can be easily configurable e.g when preparing a demo environment etc
__Step 1. Check If the Flags are available:__
- `make binary`
- ./kas-fleet-manager serve -h
- Ensure `--repeat-interval `,  `--leader_election_repeat_interval` and `--lease-renew-time` are listed.
__Step 2. Check the configurations are functional:__
- Start a [Cluster](https://console.redhat.com/openshift)
- run `ngrok http 8000`
- Find your cluster `ocm list clusters --parameter search="name like '<ClusterName>'”`
- `ocm get /api/clusters_mgmt/v1/clusters/1r3ossplpdckqqb12ci0phhilpk2n37a | jq ' .name, .id, .multi_az, .cloud_provider.id, .provider_type '`
- run `./kas-fleet-manager serve --<Flag Configurations> …

feat: Make reconciler interval, leader lease expiration time and leader election repeat interval configurable

---

internal/connector/test/integration/features/connector-api.feature
internal/kafka/constants/metrics.go
internal/kafka/internal/metrics/federate_user_metrics_test.go
pkg/client/observatorium/api.go

Expose additional metrics (for instance limits) via the federate and query endpoints.
1. Run the fleet manager locally against a cluster and create a Kafka instance
2. Check the query, query_range and federate endpoints. Make sure the following metrics are available:
```
kafka_broker_quota_hardlimitbytes
kafka_instance_spec_brokers_desired_count
kafka_instance_max_message_size_limit
kafka_instance_partition_limit
kafka_instance_connection_limit
kafka_instance_connection_creation_rate_limit
```

feat: expose instance limit metrics

---

internal/connector/test/integration/features/connector-agent-api.feature
internal/connector/test/integration/features/connector-api.feature
internal/connector/test/integration/features/connector-cluster-api.feature
internal/connector/test/integration/features/connector-multitenancy-api.feature

Raised test timeout from 5 to 10 seconds in cucumber feature tests. 
CI tests should pass in nightly builds.

fix(connectors): raised connector test timeout in waiting for API results from 5 to 10 seconds

---

internal/kafka/internal/services/quota/ams_quota_service.go

we should be using `quota_consumed` (billing related) instead of `capacity_consumed` (hardware capacity related) for anything related to Quota.

fix: use quota instead of capacity consumed

---

internal/connector/internal/api/dbapi/connector_cluster.go
internal/connector/internal/handlers/connector_cluster.go
internal/connector/internal/migrations/202203310000_add_connector_cluster_client_secret.go
internal/connector/internal/migrations/migrations.go
internal/connector/internal/services/connector_cluster.go

Saves serviceaccount client secret in connector_cluster on cluster creation to avoid looking it up when providing addon parameters.
Cluster creation tests in integration tests MUST continue to work as before. 

feat(connectors): fixes MGDCTRS-717, save agent serviceaccount secret with connector cluster

---

internal/kafka/internal/migrations/20220330101500_add_cluster_client_secret.go
internal/kafka/internal/migrations/migrations.go
internal/kafka/internal/services/clusters.go
internal/kafka/internal/services/clusterservice_moq.go
internal/kafka/internal/services/kas_fleetshard_operator_addon.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go
pkg/api/cluster_types.go

With the new SSO, client secret needs to be saved into the database because, after creation, it can't be retrieved anymore.
PR contains 2 commits:
- one contains changes generated by `make generate`
- other one contains changes for this PR
Check that when a cluster is created, the secret is saved into the database and doesn't gets recreated many times.

Saving client secret into database

---

internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kas_fleetshard_operator_addon.go
internal/kafka/internal/services/kas_fleetshard_operator_addon_test.go

We have 2 realms configured into the KeycloakService config. Only the service knows which one is the one to be used, so the realm config have to be requested to the service.

fix: get the realm config from the service when building the CR

---

internal/connector/internal/api/dbapi/connector_type.go
internal/connector/internal/config/connectors.go
internal/connector/internal/migrations/202204050000_add_connector_type_checksum.go
internal/connector/internal/migrations/migrations.go
internal/connector/internal/services/connector_cluster.go
internal/connector/internal/services/connector_namespaces.go
internal/connector/internal/services/connector_types.go
internal/connector/internal/services/connectors.go
internal/connector/internal/workers/connector_mgr.go
internal/connector/test/integration/features/connector-api.feature

Marks reconcile done in a background thread to support multiple fleet manager instances with only one with started workers.
CI should work, integration test for checksum verification should pass. 
Deployment in dev environment should be able to scaled to more than one fleetmanager.

fix(connectors): fixes MGDCTRS-331, allow scaling cos-fleet-manager pods

---

internal/kafka/test/integration/cluster_mgr_test.go

Our nightly test is failing due to issues with the cluster logging operator addon installation on ocm. Since this isn't really needed to be installed for our integration tests, we can disable it. We may re-add it later once the issue has been fixed in ocm. 
* CI checks passing

test: disable installation of cluster logging operator addon

---

Makefile
docs/deploying-kas-fleet-manager-to-openshift.md
templates/secrets-template.yml

- Adds ability to pass SUPPORTED_CLOUD_PROVIDERS to make deploy/service
- Loads KUBE_CONFIG and image-pull.dockerconfigjson secrets as base64 to make it easier to pass as multi line ENV_VARS

chore: Config updates to enable easier standalone_provider usage

---

internal/connector/test/integration/feature_test.go

Connector integration test harness explicitly sets reconcile interval to 1 second, and not just rely on the config when using a mock OCM server. 
CI tests should pass, nightly tests should pass after PR is merged. 
~~- [ ] Required Standard Operating Procedure (SOP) is added.~~~~

fix(connectors): fixes MGDCTRS-733: fixed reconcile interval configuration for connector integration tests in all environments

---

internal/kafka/internal/services/kafka_test.go
pkg/auth/audit_log_middleware_test.go
pkg/auth/context.go
pkg/auth/context_config.go
pkg/auth/context_test.go
pkg/auth/helper.go
pkg/auth/require_org_id_middleware_test.go
pkg/auth/roles_authz_middleware.go
pkg/providers/core.go
templates/service-template.yml

Make token claims in KFM configurable via flags
[MGDSTRM-7822](https://issues.redhat.com/browse/MGDSTRM-7822)
**Added flags**
```
--tenant-username-claim
--tenant-id-claim
--tenant-org-admin-claim
--alternate-tenant-username-claim
--tenant-user-id-claim
--alternate-tenant-id-claim
```
1 - `./kas-fleet-manager serve --help` to check if the flags are showing as available.
2 - `./kas-fleet-manager serve --[flag]` and observe the changes.

feat: Make token claims in KFM configurable via flag

---

.gitignore
Makefile
docs/deploying-kas-fleet-manager-to-openshift.md
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/util.go
internal/kafka/internal/services/util_test.go
pkg/client/keycloak/config.go
templates/service-template.yml

JIRA: https://issues.redhat.com/browse/MGDSTRM-7754
1) Add the special management org in the keycloak config. though not used now, this is
intended to be used later post migration - for the verification of fleetshard communication
back to KFM. Ex: Fleet shard client will be created in speical management org, and we need this
information to verify
2) Add Canary client ID in the custom claim check for Kafka CR. This improves the security that
only the canary created for this Kafka can authenticate against the broker.
1. Create a new KFM image/run KFM locally against a OSD cluster with the changes
2. Create a Kafka cluster
3. Verify the Kafka CR - custom claim check has the associated canary clientID 
Note: @akoserwal  and myself verified the changes over a call.

Add speical mgmt org to keycloak config. Add canary client ID in custom claim check in Kafka CR

---

internal/kafka/internal/config/aws_test.go
internal/kafka/internal/config/dataplane_cluster_config_test.go
internal/kafka/internal/config/kafka_lifespan_test.go
internal/kafka/internal/config/kafka_quota_test.go
internal/kafka/internal/config/kafka_test.go
internal/kafka/internal/config/kas-fleetshard_test.go
internal/kafka/internal/config/providers_test.go

feat: added missing unit tests to internal/config package
coverage before:
```
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/internal/kafka/internal/config/aws.go:24:										NewAWSConfig						0.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/internal/kafka/internal/config/aws.go:34:										AddFlags						0.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/internal/kafka/internal/config/aws.go:42:										ReadFiles						0.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/internal/kafka/internal/config/dataplane_cluster_config.go:61:							getDefaultKubeconfig					75.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/internal/kafka/internal/config/dataplane_cluster_config.go:69:							NewDataplaneClusterConfig				100.0% …
```

feat: added missing unit tests to internal/config package

---

internal/kafka/internal/clusters/provider_test.go
internal/kafka/internal/clusters/standalone_provider_test.go
internal/kafka/test/mocks/data_plane/data_plane_cluster_config.go

Increase unit test code coverage in internal/kafka/internal/clusters where possible or ignore files, for which writing unit tests is not feasible in the make test make target.
Jira: [Here](https://issues.redhat.com/browse/MGDSTRM-7975)
Test coverage:
|  File  | Test Coverage Before  | Test coverage after | 
|---|---|---|
| cluster_builder.go |  100% | 100%  |
| ocm_provider.go |  87.4% | 87.4%  |
| provider.go |  0% | 100%  |
| standalone_provider.go |  34.4% | 47.7%  |
| types.go |  100% | 100%  |
1. Run `make test`.
2. Run `make test/html/coverage/report`.
3. Can see the new lines added in the report.

test: increase test coverage in internal/kafka/internal/clusters

---

internal/connector/internal/services/connector_cluster.go
internal/connector/test/integration/features/connector-agent-api.feature

connector agent APIs get http status 410 if the cluster has been deleted
Added integration test to verify. 

fix(connectors): fixes MGDCTRS-777, connector agent APIs get http status 410 if the cluster has been deleted

---

Makefile
config/service-account-limits-check-skip-org-id-list.yaml
docs/deploying-kas-fleet-manager-to-openshift.md
pkg/client/keycloak/config.go
pkg/services/sso/keycloak_service.go
pkg/services/sso/keycloak_service_test.go
pkg/shared/config.go
pkg/shared/config_test.go
templates/service-template.yml

JIRA: https://issues.redhat.com/browse/MGDSTRM-8232
We need a list of org IDs for whom the existing 50 service account limit cannot be applied.
So we have implemented a skip list that can be controlled via the saas yaml definition in app-interface
so skip certain orgs from this restriction.
1. Set env values such as export SERVICE_ACCOUNT_LIMIT_CHECK_SKIP_ORG_ID_LIST="[01234,56789]", export MAX_ALLOWED_SERVICE_ACCOUNTS=1
2. Build KFM from the branch
3. Follow the standard steps to deploy a user built image to a OSD
4. Verify that config map is created with name "service-account-limits-check-skip-org-id-list..yaml" containing the orgIDs in the export list
5. Validate creation of service accounts
6. Check if you can create more than the limit if the orgID is present in the list
7. check if …

feat: Add skip list based on org IDs to skip the service account limits checks

---

pkg/auth/helper.go

Removed capital letters from error strings in helper.go to abide by golang standards [here](https://github.com/golang/go/wiki/CodeReviewComments#error-strings)

style: removed capital letters from error messages, helper.go

---

config/kafka-capacity-config.yaml
internal/kafka/internal/config/kafka.go
internal/kafka/internal/services/data_plane_cluster.go
internal/kafka/internal/services/data_plane_cluster_test.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/quota/quota_management_list_service_test.go
internal/kafka/test/helper.go
internal/kafka/test/integration/data_plane_cluster_test.go
internal/kafka/test/integration/kafkas_test.go
templates/service-template.yml

Remove the old `kafka-capacity-config` template. It is replaced by the supported instance types config. Some of the dynamic scaling tests were relying on this config. They are skipped for the moment as the dynamic scaling logic itself is going to change.
The service template is also updated and the values should be removed from app-interface too.
Passing tests should be sufficient.

Remove unused config files

---

internal/connector/internal/services/connector_cluster.go
internal/connector/internal/services/connector_namespaces.go
internal/connector/internal/services/connectors.go
internal/connector/test/integration/features/connector-agent-api.feature

The problem was happening specifically in case of expired namespaces that had connectors previously assigned.
The namespace expires and its status is set to deleting, the control plane delete the namespace and the status is updated to deleted. At this point  the namespace reconcile loop should run and correctly delete the namespace, unfortunately what happens inside the reconcile loop is that the namespace is re-detected as expired and placed back in deleting state before actually trying to delete it. In a never ending loop.
This PR fix this behavior.
See https://issues.redhat.com/browse/MGDCTRS-834
1. OCM_ENV=integration make test/integration/connector

fix(connectors): fix https://issues.redhat.com/browse/MGDCTRS-834

---

pkg/quota_management/quota_management_list_config_test.go
pkg/quota_management/quota_management_list_test.go

Increase unit test code coverage in pkg/quota_management where possible or ignore files, for which writing unit tests is not feasible in the make test make target.
Jira: [Here](https://issues.redhat.com/browse/MGDSTRM-7987)
Test coverage:
| Files  | Test Coverage Before  | Test coverage After  | 
|---|---|---|
| account.go  | 100%  | 100%  | 
| organisation.go  | 100%  | 100%  | 
| quota_management_list_config.go  | 0%  | 85% | 
| quota_management_list.go  | 0%  | 100%  | 
1.Run `make test`.
2.Run `make test/html/coverage/report`.
3.Can see the new lines added in the report.

test: Increase test coverage in pkg/quota_management

---

internal/kafka/constants/metrics.go
internal/kafka/internal/presenters/metric.go
internal/kafka/internal/presenters/metric_test.go

The following changes fixes the issue when collecting and converting user facing metrics to Prometheus format for the /federate endpoint. This was caused by the same metric returning multiple results with the same values for its labels.
Example error caused by this: 
```
* collected metric "kafka_broker_client_quota_limit" { label:<name:"statefulset_kubernetes_io_pod_name" value:"jb-eval-1-kafka-0" > label:<name:"strimzi_io_cluster" value:"jb-eval-1" > gauge:<value:1.048576e+07 > } was collected before with the same name and label values
* collected metric "kafka_broker_client_quota_limit" { label:<name:"statefulset_kubernetes_io_pod_name" value:"jb-eval-1-kafka-0" > label:<name:"strimzi_io_cluster" value:"jb-eval-1" > gauge:<value:1.7976931348623157e+308 > } was collected before with the …
```

fix: add additional labels to differentiate metric results for federate endpoint

---

internal/connector/test/integration/features/connector-api.feature
pkg/errors/errors.go

the single/multi AZ errors are no longer used since the request param has been deprecated.

fix: remove unused availability zone errors

---

internal/connector/internal/services/connector_types.go
internal/connector/internal/workers/connector_mgr.go
internal/connector/test/integration/cucumber_steps.go
internal/connector/test/integration/feature_test.go
internal/connector/test/integration/features/connector-api.feature
test/helper.go

fixed https://issues.redhat.com/browse/MGDCTRS-454
Added an help facility to be able to setup an initial DB state in tests by providing a slice of sql statements that get executed sequentially before the application is started. This can be useful to test reconciliation scenarios that happens at application strartup time.
1. `OCM_ENV=integration make test/integration`

fix(connectors): fix MGDCTRS-454: Inconsistent connector catalog, delete unused connector types.

---

internal/connector/internal/config/connectors_quota_config.go

Removed capital letters from error strings in connectors_quota_config.go to abide by golang standards [here](https://github.com/golang/go/wiki/CodeReviewComments#error-strings)

style: removed capital letters from error messages, connectors_quota_config.go

---

internal/kafka/internal/config/providers_test.go

If an unexpected error occurs, got will be nil and the Expect(got).To... will fail, halting the test execution.
That means that the Expect(err != nil) won't be executed, resulting in confusing errors (error will fail for unmatched got instead than unexpected error).

refactor: reposition Expect(<values>) to below errors, in providers_test.go

---

internal/kafka/internal/services/clusters.go
internal/kafka/internal/services/clusterservice_moq.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go

1. As reported in https://issues.redhat.com/browse/MGDSTRM-8409, for a new
OSD cluster, the fleet-manager will report 404 until the cluster is full
terraformed. These errors make it hard to investigate issues as they
could be misleading. So let's make sure that the client_id and
client_secret are stored in the database as soon as they are available
to avoid these 404 errors from being sent to the fleetshard sync.
2. By storing the client_id, client_secret as soon as they are
available and not wait for the operators installation readiness which
can take a few minutes, we are sure to only generate the client_id and
client_secret only once. This avoids cases where we attempted to
generate the client each time until the operators where ready because
the client weren't stored in the database. …

fix(clusters): do not wait for operators to become ready to store FSO sync client_id/client_secret

---

internal/connector/internal/handlers/connector_admin.go
internal/connector/internal/handlers/connectors.go
internal/connector/internal/presenters/connector.go
internal/connector/internal/presenters/connector_deployment.go
internal/connector/internal/services/connector_types.go
internal/connector/internal/services/connectors.go
internal/connector/internal/services/vault/config.go
internal/connector/internal/services/vault/vault_service.go
internal/connector/internal/services/vault/vault_service_aws.go
internal/connector/internal/services/vault/vault_service_test.go
internal/connector/internal/services/vault/vault_service_tmp.go
pkg/api/json.go

- chore(connectors): pre-allocate slice as we know the size
- chore(connectors): remove kafka_id and connector_type_id from conenctors list as they are not documented in the OpenAPI and can be replacend by the search functionnality
- chore(connectors): use constants for vault kind and default aws region instead of hardcoded strings
- chore(connectors): error string should not be capitalized
- feat: add utility method to api.JSON to unmarshal to a value

connectors: minor fixes and improvements

---

internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr.go

This check causes all Kafkas that are marked as deprovision to be removed immediately without waiting for fleetshard to report that resources on the data plane cluster has been deleted for clusters. This check has been removed to prevent this.
Kafkas will only move from 'preparing' to 'provisioning' if the boostrapserver host is set. Therefore the only check we should do is to see if the bootstrap server host is set. This would mean that resources haven't been created on the data plane cluster yet so we can remove the kafka immediately.
1. Verify that Kafkas with `preparing` status can be deleted successfully
2. Verify that Kafkas with `provsioning`/`ready` status can be deleted successfully

fix: remove check for EnableAuthenticationOnKafka from kafka deletion reconcile

---

docs/deploying-kas-fleet-manager-to-openshift.md
docs/feature-flags.md
internal/kafka/internal/api/dbapi/kafka_request_types.go
internal/kafka/internal/config/kafka_supported_instance_types.go
internal/kafka/internal/config/kafka_supported_instance_types_test.go
internal/kafka/internal/presenters/kafka.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/kafkaservice_moq.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go
templates/service-template.yml

Related to https://issues.redhat.com/browse/MGDSTRM-8483
Kafka lifespans for a given instance size are now specified through the `config/kafka-instance-types-configuration.yaml`.
KFM code was still using the environment variable `KAFKA_LIFE_SPAN` to calculate expiration time of existing kafka instances to mark them for deprovisioning.
This PR updates the expiration logic to use lifespan set in `config/kafka-instance-types-configuration.yaml` instead.
Some important additional remarks:
* The `--enable-deletion-of-expired-kafka` flag that controls whether expiration logic is applied or not has been kept. The alternative would be removing this completely.
1.
Create a kafka standard instance
Create 3 developer instances
Then update the created_at time in the DB to a time older than 2 days …

feat: update kafka automated deprovision expiration logic to make use of instance types config

---

internal/kafka/internal/config/dataplane_cluster_config.go
internal/kafka/internal/config/dataplane_cluster_config_test.go

Remove image pull secret so that any changes to this file can be ignored by git. This is already included in the [.gitignore](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/.gitignore#L60)
1. Ensure any changes to image pull secret file is not included in git changes

chore: remove image pull secret

---

Makefile
internal/kafka/internal/config/kafka.go
internal/kafka/internal/config/kafka_lifespan.go
internal/kafka/internal/config/kafka_lifespan_test.go
templates/service-template.yml

Related to https://issues.redhat.com/browse/MGDSTRM-8619.
After changes made in https://issues.redhat.com/browse/MGDSTRM-8483 the KAFKA_LIFE_SPAN template parameter (and its corresponding code in KFM) is not needed anymore. This PR performs the cleanup
Check there are no references to KAFKA_LIFE_SPAN or kafka-lifespan and any of its related logic

chore: remove global KAFKA_LIFE_SPAN parameter and cli flag

---

Makefile

DATA_PLANE_PULL_SECRET is intended to be a shell variable and not
a Makefile variable. Shell variables should be referenced
with the $${<var-name>} syntax. The $(<var-name>) syntax is
intended for Makefile variables
Open a shell and assign a docker login configuration file content to the DATA_PLANE_CLUSTER variable. For example:
export DATA_PLANE_CLUSTER='mylong
multiline
dockerlogin
config
filecontent
'
Then run the `dataplane/imagepull/secret/setup` target:
make dataplane/imagepull/secret/setup
No errors should occur.

fix: fix dataplane/imagepull/secret/setup Makefile target

---

internal/kafka/internal/services/cloud_providers_test.go
internal/kafka/internal/services/clusters_test.go
internal/kafka/internal/services/data_plane_cluster_test.go
internal/kafka/internal/services/kafka_instance_type_test.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/kas_fleetshard_operator_addon_test.go
internal/kafka/internal/services/observatorium_service_test.go
internal/kafka/internal/services/quota/quota_management_list_service_test.go
internal/kafka/test/mocks/cloud_providers/cloud_providers.go
internal/kafka/test/mocks/clusters/clusters.go

Increase unit test code coverage in internal/kafka/internal/services where possible or ignore files, for which writing unit tests is not feasible in the make test make target.
Jira: [Here](https://issues.redhat.com/browse/MGDSTRM-7980)
1. Run make test.
2. Run make test/html/coverage/report.
3. Should be able to see the improved test coverage.

test: Increase unit test coverage in internal/kafka/internal/services

---

.codecov.yml

In PR https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1033 it's been observed that if coverage decreases PRs are blocked.
This PR changes this behavior to set codecov PR checks as purely informational.

feat: Set codecov PR checks as informational

---

go.mod
go.sum
internal/kafka/internal/services/quota/ams_quota_service.go

bumps the ocm sdk and adds the billing account id to the related resource when creating a subscription.

fix: record billing account id in related resource

---

internal/kafka/internal/config/kafka.go

Go to main branch and run:
```
grep -R -i KafkaCapacityConfig *
```
Only a single result should be shown and it should be the definition of the type being removed

chore: remove unused KafkaCapacityConfig in internal config kafka pkg

---

internal/kafka/internal/config/kafka.go

The `KafkaConfig` type in the config package contained json struct tags. json struct tags are used when serializing/deserializing a JSON file. However, `KafkaConfig` is not serialized/deserialized from any file so they are not needed.
This PR removes them.
Verify that kas fleet manager still works

chore: remove json struct tags from kafka config type

---

internal/kafka/internal/config/aws.go
internal/kafka/internal/config/dataplane_cluster_config.go
internal/kafka/internal/config/kafka_quota.go
internal/kafka/internal/config/kas-fleetshard.go
internal/kafka/internal/config/providers.go

Some configuration types in the internal kafka config package had json struct tags but we didn't use those types to serialize/deserialize JSON.
This PR removes the json struct tags for them.
Aside from that, the `Provider` type in the config package had json struct tags but the content of the providers configuration file is expected to be in `yaml` so it was not correct. The PR also changes that type to use `yaml` struct tags. Even if this was not correct it still worked because the Go json serializer/deserializer uses the name of the struct attribute in lowercase as a corresponding json key, and the keys that were specified had the same name (in lowercase).
Verify kas fleet manager still works and returns correct information from the endpoints.

Remove unused jsonstructtags from configs

---

internal/kafka/internal/converters/cluster.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/kafkaservice_moq.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go
internal/kafka/test/integration/cluster_metrics_test.go

Fixes https://issues.redhat.com/browse/MGDSTRM-8866
This depends on https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1100 for the test to pass, so I'll open it as draft.

fix(metrics): cluster_status_capacity_used doesn't update when kafka count goes down to 0

---

internal/kafka/internal/clusters/ocm_provider.go
internal/kafka/internal/clusters/ocm_provider_test.go
internal/kafka/internal/clusters/provider.go
internal/kafka/internal/clusters/provider_moq.go
internal/kafka/internal/clusters/standalone_provider.go
internal/kafka/internal/clusters/standalone_provider_test.go
internal/kafka/internal/clusters/types/types.go
internal/kafka/internal/config/dataplane_cluster_config.go
internal/kafka/internal/config/dynamic_scaling_config.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go
pkg/client/ocm/client.go
pkg/client/ocm/client_moq.go

Related to https://issues.redhat.com/browse/MGDSTRM-7434
This PR implements the automated creation of non default MachinePools when KAS Fleet Manager is run in data plane scaling mode `auto`.
Characteristics of the implementation:
* At the moment no creation of non default MachinePools is performed when the scaling mode is `manual` or `none`. It might be a good have to implement it in the future
* The creation and retrieval of MachinePools is done in a cluster provider-agnostic way, by using the `Provider` interface (in internal/kafka/internal/clusters/provider.go)
* At the moment there is no implementation for the `standalone` cluster provider. The current implementation has a noop . It implementation of the methods for it. If a user were to run kas fleet manager with `standalone` …

feat: perform non default machinepool creation in autoscaling mode

---

internal/kafka/internal/clusters/cluster_builder.go
internal/kafka/internal/clusters/cluster_test.go

Developer instance do not require multi_az clusters and thus they can be provisioned on a single az cluster. We need to be able to create single_az cluster for developer instances. At the moment, only multi_az clusters are created.
Jira: https://issues.redhat.com/browse/MGDSTRM-8916

feat: option for multi_az/single_az + tests

---

internal/kafka/internal/clusters/cluster_builder.go
internal/kafka/internal/clusters/cluster_test.go

Auto-scaled default machine pool created
- Min Replicas: 6
- Max Replicas: 18
[MGDSTRM-8917](https://issues.redhat.com/browse/MGDSTRM-8917)
`make db/teardown`
`make sso/teardown`
`make db/setup`
`make ocm/setup OCM_OFFLINE_TOKEN=token OCM_ENV=development`
`make sso/setup`
`make sso/config`
`make keycloak/setup MAS_SSO_CLIENT_ID=kas-fleet-manager MAS_SSO_CLIENT_SECRET=kas-fleet-manager OSD_IDP_MAS_SSO_CLIENT_ID=kas-fleet-manager OSD_IDP_MAS_SSO_CLIENT_SECRET=kas-fleet-manager`
`make run`
`make db/login`
`SELECT cluster_id from clusters;`
`ocm get /api/clusters_mgmt/v1/clusters/<ClusterID>/`
```json
.....
.....
"nodes": {
"master": 3,
"infra": 3,
"autoscale_compute": {
"min_replicas": 6,
"max_replicas": 18
},
.....
.....
},
.....
.....
```

feat: Create an autoscaled default machine pool

---

pkg/metrics/metrics.go

The two metrics were calculated in the KafkaManager reconciler but the
metrics were reset from the clusters reconciler.
By moving this to the correct resets methods, the metrics will get properly reset when the leader changes for the KafkaManager reconciler.
Which in turn will ensures that the old leader pod does not show stale data when it's scraped
Code review should be enough
- …

fix(metrics): reset capacity used and capacity available metrics for KafkaManager reconciler

---

internal/kafka/internal/services/quota/ams_quota_service.go

avoid redundant call to `GetOrganisationIdFromExternalId`

fix: avoid redundant api call

---

go.mod
go.sum

Details on https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/security/dependabot/2
See the proposed version on https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/security/dependabot/2

build(deps): update github.com/docker/distribution to fix OCI Manifest Type Confusion Issue

---

internal/kafka/internal/services/data_plane_kafka.go
internal/kafka/internal/services/data_plane_kafka_test.go

Here we are checking the DataplaneKafkaStatus for why a kafka has been rejected.
If the kafka is noted as rejected due to `Cluster has insufficient resources` the status returned will be "statusReassigningCluster"
[MGDSTRM-9030](https://issues.redhat.com/browse/MGDSTRM-9030)
Unit tests have been added

feat: Check if kafka fails to be provisioned due to cluster fullness

---

internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go
internal/kafka/test/common/kafka_pollers.go
internal/kafka/test/integration/cluster_mgr_test.go
pkg/metrics/metrics.go

Fixes https://issues.redhat.com/browse/MGDSTRM-7480 and
https://issues.redhat.com/browse/MGDSTRM-7481
This relies on the `MaxUnits` information which will be present in the database when dynamic scaling is turned on and FSO reports it back to us.
Unit and integration tests passing

feat(cluster-metrics): add cluster capacity metrics for when dynamic scaling is turned on

---

Makefile

It was decided that these files are unable to be tested and can be ignored instead.
Closes these jiras:
1. https://issues.redhat.com/browse/MGDSTRM-9002
2. https://issues.redhat.com/browse/MGDSTRM-9004
3. https://issues.redhat.com/browse/MGDSTRM-9005

test: ignore files in pkg/db

---

internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/kafkaservice_moq.go
internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr_test.go
internal/kafka/test/integration/data_plane_endpoints_test.go

Here we Re-assign a Kafka to another OSD cluster when Rejected with ClusterFull reason:
Combined with previous prs, we: 
- Check if kafka fails to be provisioned due to insufficient cluster resources  [here](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1156#issue-1291093659)
- Remove the assigned cluster from the kafka [here](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1163#issue-1293184236)
- And with this pr we reassign the kafka to a new cluster.
[MGDSTRM-9034](https://issues.redhat.com/browse/MGDSTRM-9034)
Unit and Integration tests passing.

feat: Re-assign Kafka to another OSD cluster when Rejected with ClusterFull reason

---

config/provider-configuration.yaml
internal/kafka/internal/config/providers.go
internal/kafka/internal/config/providers_test.go

As part of dynamic scaling, the concept of a minimum
available capacity slack in streaming units has been introduced.
The available capacity slack of a supported instance type in a region
is the desired minimum number of streaming units that should
be available(free) at any moment for that instance type in the region.
It has been introduced in the provider configuration file of the
fleet manager. There is one capacity slack value per defined instance
type in the region.
The attribute is optional. If it is not set then it is interpreted
as a capacity slack of 0 is desired.
The capacity slack is intended to be used only when dynamic scaling
is enabled.
The capacity slack is defined as the `min_available_capacity_slack_streaming_units` yaml attribute  
This will require app-interface …

feat: add minimum available capacity slack concept

---

cmd/kas-fleet-manager/main_test.go
internal/kafka/internal/migrations/20220720180000_dynamic_scaleup_worker_to_leader_leases.go
internal/kafka/internal/migrations/migrations.go
internal/kafka/internal/workers/cluster_mgrs/dynamic_scaleup_mgr.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/providers.go
pkg/workers/leader_election_mgr.go

Part of https://issues.redhat.com/browse/MGDSTRM-9133.
Adds the base structure of a dynamic scale up reconciler where dynamic scale evaluation and trigger actions will be performed in the near future.
1. Run kas fleet manager and verify that it starts correctly
2. Look at the leader leases table and verify that there is an entry with the lease name 'dynamic_scale_up'
3. Verify that when kas fleet manager is started with dynamic scaling enabled is started the following is logged `running dynamic scale up reconcile event`
4. Verify that when kas fleet manager is started with dynamic scaling disabled the following is logged `dynamic scaling is disabled. Dynamic scale up reconcile event skipped`

feat: Add dynamic scaleup reconciler structure

---

internal/kafka/internal/workers/cluster_mgrs/dynamic_scaleup_mgr.go
internal/kafka/internal/workers/cluster_mgrs/dynamic_scaleup_mgr_test.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go

On a recent PR in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1197 we created a new reconciler for dynamic scaleup tasks.
This PR moves the `reconcileClustersForRegions` originally found in the clusters mgr to the dynamic scale up manager.
* fleet manager starts correctly.
* tests pass

refactor: move reconcileClustersForRegions from clusters mgr to dynamic scaleup manager

---

internal/kafka/internal/workers/clusters_mgr.go

Set min nodes to 1 in order to allow the autoscaler to consider the machineset for autoscaling
Depending on wether we are multi_az or single_az, the ocm provider will perform the round up to the multiple of 3

fix(autoscaling): set min nodes to 1 in order to allow the autoscaler to consider the machineset for autoscaling

---

internal/kafka/internal/workers/clusters_mgr.go

This ensures that the dns is persisted in the database for the reconciliation of cluster identity
provider to make use of it directly, instead of it doing the reconciliation steps as well.
Test should continue to pass

refactor(cluster_mgr): reconcile cluster dns first before cluster identity provider

---

internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go

Harden setKafkaPerClusterCountMetrics to not err when ClusterID is empty.
This avoids sending out an error for kafkas counts that have not been assigned to an OSD cluster
yet. Follows up on
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1167#issuecomment-1190536398 and
address the first error shown there

fix(cluster_mgr): harden setKafkaPerClusterCountMetrics to not err when ClusterID is empty

---

Makefile

This PR fixes some cases where the TESTFLAGS values were not being correctly interpreted when running the Makefile targets related to testing.
Makefile test-related targets still work as expected and TESTFLAGS can still be provided

fix: Makefile not being able to process some test flags correctly in test targets

---

internal/connector/internal/api/admin/private/api/openapi.yaml
internal/connector/internal/api/admin/private/api_connector_clusters_admin.go
internal/connector/internal/handlers/connector_admin.go
internal/connector/internal/handlers/connector_agent.go
internal/connector/internal/services/connector_cluster.go
internal/connector/internal/services/connector_namespaces.go
internal/connector/test/integration/features/connector-agent-api.feature
openapi/connector_mgmt-private-admin.yaml

Add support for force query option for deleting namespaces, to allow users to remove clusters if data plane OSD has been deleted. 
To be safe and avoid accidentally deleting an entire cluster, the process is multi-step requiring force deleting connectors, then deleting namespaces, and finally force deleting namespaces. After all namespaces have been deleted in a cluster, including the default namespace, control plane will reconcile the deleting cluster. 
Included CI integration test should pass.

feat(connectors): fixes MGDCTRS-912, add support for force query option for deleting namespaces

---

internal/kafka/internal/handlers/cloud_providers_test.go
internal/kafka/internal/services/cluster_placement_strategy.go
internal/kafka/internal/services/cluster_placement_strategy_moq.go
internal/kafka/internal/services/cluster_placement_strategy_test.go
internal/kafka/internal/services/clusters.go
internal/kafka/internal/services/clusterservice_moq.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr_test.go
internal/kafka/test/common/util.go

Changes the following methods to return an `error` type instead of the KAS Fleet Manager `ServiceError`. This is based on what was agreed upon in the Control Plane team's technical discussion. Functions should not return `ServiceError` unless there is a strong need for it which wasn't the case for these functions.
Cluster Service
- FindAllClusters: will now return database error as is. This is only called in the cluster placement strategy methods which now returns an `error` type.
- FindCluster: will now return database error as is. This is called in the following places:
- Cluster placement strategy: This now returns an `error` type.
- Cluster manager: in the reconcileDeprovisioningCluster, this method already returns an `error` type.
- FindKafkaInstanceCount: will return database error …

refactor:return error type for FindCluster in cluster placement strategy interface

---

internal/kafka/internal/services/clusters.go
internal/kafka/test/integration/cluster_service_test.go

Ignore kafkas in deleting state in streaming unit count. The kafkas in those status can be ignored as they do not consume resources in the data plane since once they are in this state, they've been already fully removed from the data plane. Eventually, they'll be soft deleted from our database if external resources e.g aws dns entries, sso clients
have been removed.
Closes https://issues.redhat.com/browse/MGDSTRM-9252
Integration test should pass in both environments 

fix(clusters): ignore kafkas in deleting state in streaming unit count

---

internal/kafka/internal/workers/clusters_mgr.go

The key should be "bf2.org/kafkaInstanceProfileType" and not "bf2.org/kafkaInstanceProfile"

fix(machinepool): correct machinepool label key

---

internal/kafka/constants/kafka.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr_test.go

The option that's chosen here is the one that:
- Does not change how manual mode works
- Add an IF statement to check for scaling mode, if dynamic scaling accept the kafka anyway if region limits not reached
- Add a reconciliation steps that checks for Kafkas in accepted that do not have ClusterID set and assigns the ClusterID. Do this irrespective of the scaling mode and do this within some reasonable timeout of an hour (enough for a new cluster to be provisioned and terraformed).
Closes https://issues.redhat.com/browse/MGDSTRM-8914
Added unit tests should pass
- ~~[ ] JIRA has been created for changes …

feat: accept a kafka even if there is no ready cluster but region limits not reached during dynamic scaling

---

config/node-prewarming-configuration.yaml
internal/kafka/internal/config/node_prewarming_config.go
internal/kafka/internal/config/node_prewarming_config_test.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go

Rename the attribute designed to specify the reserved capacity in the
node prewarming configuration from reserved_streaming_units to
num_reserved_instances to accurately represent what is
being reserved.
This change does not break any existing configuration/behavior as dynamic scaling is still not enabled.
All tests pass, all KFM functionality related to node prewarming still works.

refactor: rename reserved capacity attribute num_reserved_instances in node prewarming config

---

.github/workflows/ci.yaml
Makefile

Following https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1088 we stoped linting OpenShift templates unintentionally when CI is run.
This PR brings back linting of openshift templates in CI
Inspect CI output and verify that
```
bin/spectral lint templates/*.yml templates/*.yaml --ignore-unknown-format --ruleset .validate-templates.yaml
No results with a severity of 'error' or higher found!
```
is run.

ci(lint): add linting step in CI to lint OpenShift templates

---

Makefile
internal/kafka/internal/config/kafka.go
internal/kafka/internal/config/kafka_quota.go
internal/kafka/internal/config/kafka_quota_test.go
internal/kafka/internal/environments/development.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
templates/service-template.yml

Add dynamic flag max-allowed-developer-instances and set default value one.
https://issues.redhat.com/browse/MGDSTRM-8159
set max-allowed-developer-instances flag value and will bale to create kafka trial instances based on flag value. 
If you will try to create kafka trial instances more than flag value , it should return error.

fix: add dynamic flag max-allowed-developer-instances

---

internal/connector/internal/config/connectors_test.go
internal/kafka/test/common/util.go
internal/kafka/test/integration/data_plane_cluster_test.go
pkg/acl/access_control_list_middleware_test.go
pkg/api/cluster_types.go
pkg/constants/db_context_keys.go
pkg/db/context.go
pkg/db/transaction_middleware.go
pkg/handlers/errors_test.go
pkg/handlers/openapi_handler_test.go
pkg/logger/logger.go
pkg/logger/logger_test.go
test/mocks/api_server.go
test/mocks/jwk_cert_server.go

This PR is to Investigate and fix pieces of code currently omitted by the linter, i.e lines that have `//nolint`
Jira: https://issues.redhat.com/browse/MGDSTRM-900

fix: fix pieces of code currently omitted by the linter

---

internal/connector/internal/handlers/connector_cluster.go
internal/connector/internal/services/connector_cluster.go
internal/connector/internal/workers/cluster_mgr.go
internal/connector/test/integration/cucumber_steps.go
internal/connector/test/integration/feature_test.go
internal/connector/test/integration/features/connector-admin-api.feature
internal/connector/test/integration/features/connector-agent-api.feature
internal/connector/test/integration/features/connector-cluster-api.feature
internal/connector/test/integration/features/connector-multitenancy-api.feature
pkg/services/sso/redhatsso_service.go
pkg/services/sso/redhatsso_service_test.go

Delete cluster service account using client id stored in the cluster table instead of creating an old mas-sso style service account client id from cluster id.
CI should pass for standard tests. 
For manual verification with redhat sso provider:
1. Set envirnonment variables 
```
SSO_PROVIDER_TYPE=redhat_sso
SSO_BASE_URL=https://sso.stage.redhat.com
```
2. Use a redhat sso stage environment client id and secret using the command:
```
make redhatsso/setup SSO_CLIENT_ID=xxxx SSO_CLIENT_SECRET=xxxx
```
3. Run connector integration tests using the command:
```
make test/integration/connector
```
~~- [ ] All PR comments are resolved either by addressing them or creating follow up tasks~~
~~- [ ] Required metrics/dashboards/alerts have been added (or …

fix(connectors): fixes MGDCTRS-1146, delete cluster service account using client id stored in the cluster table

---

pkg/client/ocm/client.go
pkg/client/ocm/client_moq.go

This PR adds a method that calls AMS' ​/api​/accounts_mgmt​/v1​ endpoint in the ocm client
This endpoint returns a summary of the quota used by resources in ocm, including the max allowed and consumed quota. This information is what we need to expose in the kas fleet manager metrics.
Jira: https://issues.redhat.com/browse/MGDSTRM-9402

feat: Add GetQuotaCost method to the ocm client

---

docs/feature-flags.md
internal/kafka/internal/clusters/cluster_builder.go
internal/kafka/internal/clusters/cluster_test.go
internal/kafka/internal/config/dataplane_cluster_config.go
internal/kafka/internal/environments/development.go
internal/kafka/internal/environments/integration.go
internal/kafka/internal/environments/production.go
internal/kafka/internal/environments/stage.go
internal/kafka/internal/workers/clusters_mgr.go
templates/service-template.yml

Now that we will have AWS and GCP Data Plane Clusters the CLUSTER_COMPUTE_MACHINE_TYPE name is too general. This PR renames it to AWS_CLUSTER_COMPUTE_MACHINE_TYPE and also its related CLI flags and Go data types.
Related to https://issues.redhat.com/browse/MGDSTRM-9362
KFM still runs correctly and there are no errors.

refactor: rename cluster machine type flag to be aws specific

---

Makefile

The extra indentation was causing the docker image build to fail. Fixes the following build failure: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/runs/7839389608?check_suite_focus=true
- Ensure it builds successfully

fix: remove extra indentation on specinstall make target

---

Makefile
docs/deploying-kas-fleet-manager-to-openshift.md
templates/observatorium-token-refresher.yml

Make replicas configurable for the Observatorium token refresher deployment so that we can increase/decrease this whenever we need.
Rolling update strategy and pod affinity has also been configured.
Note that [topology.kubernetes.io/zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone) is available from Kubernetes v1.17 (our clusters in stage/prod are running v1.2+)
Related JIRA Issue: [MGDSTRM-8444](https://issues.redhat.com/browse/MGDSTRM-8444)
- Ensure deployment is successful
- Ensure 1 replica of the token refresher is running
- Ensure deployment is successful
- Ensure 3 replicas of the token refresher is running

feat: make replicas configurable for token refresher

---

internal/kafka/internal/cloudproviders/types.go
internal/kafka/internal/cloudproviders/types_test.go
internal/kafka/internal/clusters/cluster_builder.go
internal/kafka/internal/clusters/cluster_test.go
internal/kafka/internal/clusters/ocm_provider_test.go
internal/kafka/internal/clusters/provider.go
internal/kafka/internal/clusters/provider_test.go
internal/kafka/internal/config/configuration_test.go
internal/kafka/internal/config/dataplane_cluster_config.go
internal/kafka/internal/config/dataplane_cluster_config_test.go
internal/kafka/internal/config/gcp.go
internal/kafka/internal/config/gcp_test.go
internal/kafka/internal/config/providers.go
internal/kafka/internal/services/cloud_providers.go
internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go

Update cluster builder and machinepools logic to support GCP.
Related to https://issues.redhat.com/browse/MGDSTRM-9129, https://issues.redhat.com/browse/MGDSTRM-9374.
Changes:
* Update the Cluster Builder logic to be able to provide GCP credentials when GCP is used
* Add `DefaultComputeMachineType` method in the Data Plane Cluster config type that returns the default compute instance type depending on the provided cloud provider
1. Modify the cloud providers configuration to support GCP. Additionally limit the kafka intsances for all instance types in all cloud providers to 0 except from the developer instances in GCP to prevent automatic creation of clusters:
```
supported_providers:
- name: aws # name of the cloud provider
default: true # only one default cloud provider is allowed …
```

feat: update cluster builder and machinepools logic to support GCP

---

cmd/kas-fleet-manager/main_test.go
config/provider-configuration.yaml
internal/kafka/test/helper.go

Adds GCP to the supported cloud providers example. Validation is already present and no further changes were required.
1. Add an entry to `dataplane-clusters-configuration.yaml` like
```
- name: anyname
cluster_id: dummyid
cloud_provider: gcp
region: us-east1
multi_az: true
schedulable: true
kafka_instance_limit: 2
status: "ready"
provider_type: "ocm"
supported_instance_type: "developer,standard"
```
2. Create a file named `gcp.api-credentials` under secrets:
```
{
"type": "service_account",
"project_id": "dummy",
"private_key_id": "dummy",
"private_key": "dummy",
"client_email": "dummy@gmail.com",
"client_id": "dummy",
"auth_uri": "dummy",
"token_uri": "dummy",
"auth_provider_x509_cert_url": "dummy",
"client_x509_cert_url": "dummy"
}
```
3. Run the fleet manager and query the …

feat: add gcp example

---

internal/kafka/internal/config/dataplane_cluster_config.go

When using `standalone` cluster provider type the OLM information around fleetshard and strimzi operators installation was outdated.
This PR updates that information.
Configure a manual cluster with provider type `standalone` (https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/docs/data-plane-osd-cluster-options.md#connecting-to-a-standalone-cluster) and then run kas fleet manager in cluster scaling mode 'manual'.
Verify that the cluster ends up in `ready` state and the operators are installed successfully through OLM.

feat: update data plane operators OLM images for standalone cluster provider

---

internal/kafka/internal/handlers/kafka.go
internal/kafka/internal/handlers/validation.go
internal/kafka/internal/handlers/validation_test.go

Some of the kafka validators were receiving a pointer to services.KafkaService. services.KafkaService is an interface which is a pointer type already so there is no need to pass a pointer to it.
All tests pass

refactor: refactor some kafka validators to directly use kafka service interface value

---

internal/kafka/internal/workers/clusters_mgr.go
internal/kafka/internal/workers/clusters_mgr_test.go
internal/kafka/test/integration/cloudprovider_test.go
internal/kafka/test/integration/kafkas_test.go
pkg/client/ocm/config.go
pkg/client/ocm/config_test.go
pkg/metrics/metrics.go
test/mocks/api_server.go

Adds kas_fleet_manager_quota_consumed to the KAS Fleet Manager metrics. This represents the quota currently used by the organisation of the ocm account used by KAS Fleet Manager.
Jira: [Here](https://issues.redhat.com/browse/MGDSTRM-9404)
1.Run kas fleet manager with ocm credentials specified
2.Curl http://localhost:8080/metrics
3.Ensure the quota metric as defined above are included in the response with correct values

feat: add cluster_provider_resource_quota_consumed_ metric

---

internal/kafka/internal/services/quota/ams_quota_service.go
internal/kafka/internal/services/quota/ams_quota_service_test.go
pkg/client/ocm/types.go
pkg/client/ocm/types_test.go

In order to support Kafka instances created in GCP one of the needed steps is performing quota reservation for a rhosak cluster in AMS. To do so, some new changes are needed in the KFM code related to the building of AMS ReservedResources as part of the ClusterAuthorization AMS request. This PR takes care of the needed changes.
Related to https://issues.redhat.com/browse/MGDSTRM-9368
Run KFM using the flag `--quota-type=ams`
Then Verify Kafka clusters can be created in both AWS and GCP and that AMS subscriptions are correctly created for them. Do it also for single and multiaz clusters.
Then retrieve the ReservedResources related to the AMS subscriptions and verify that when the kafka cluster is created in AWS then the resource_type value is `cluster.aws`. When it is created in GCP verify …

feat: add GCP cluster support when reserving a RHOSAK in GCP for AMS

---

internal/kafka/internal/clusters/ocm_provider.go
internal/kafka/internal/clusters/ocm_provider_test.go
internal/kafka/internal/clusters/standalone_provider_test.go
pkg/client/ocm/client.go
pkg/client/ocm/client_moq.go

Some minor changes in the OCM client logic:
* Rename `GetQuotaCost` method to `GetQuotaCosts` as the result is a collection and not a singular type
* Reuse `GetQuotaCost` in the `GetQuotaCostsForProduct` method. In this way we de-duplicate logic
Tests pass

refactor: minor QuotaCost changes

---

internal/kafka/constants/cluster.go
internal/kafka/internal/clusters/cluster_builder.go
internal/kafka/internal/clusters/cluster_test.go

Reduce the min size of the default machine pool to 3. This goes in line with https://issues.redhat.com/browse/MGDSTRM-9519 and we'd like to let the autoscaler scale the machine pool from the minimum number of nodes as possible, and 3 seemed
reasonable enough.
Tests to continue passing

feat(autoscaling): reduce the min size of the default machine pool to 3

---

Makefile

Since Go 1.16 it is automatically set to on
Makefile targets still work appropriately

chore: remove unneeded GO111MODULE envvar in Makefile

---

Makefile

Precompiling packages with -i flag is not needed anymore as
Go caches precompiled packages automatically now
Integration tests run successfully

chore: remove test/prepare Makefile target

---

.github/workflows/ci.yaml
db_setup_docker.sql
scripts/local_db_setup.sh

Increase the max_connections limit for both local and CI Postgres container to resolve issues with integration tests reaching the default (100) limit.
Value for the max_connections ranges from 1..262143. Setting the value to 200 for now as our integration tests only require around 105.
Note that this is only a temporary fix until the underlying issue has been resolved (see [MGDSTRM-9553](https://issues.redhat.com/browse/MGDSTRM-9553))
Run the following commands to verify local db set up.
1. `make db/setup`
2. `make db/login`
3. `show max_connections;`
- Value should be 200
For CI changes, see the Lint & Test run of this PR. 
- `Show inital max_connections value` step should show the default value
- `Show max_connections after new configuration has been applied` step should show the new …

Increase db max connections limit

---

internal/kafka/internal/clusters/ocm_provider.go
internal/kafka/internal/clusters/ocm_provider_test.go
internal/kafka/internal/clusters/provider.go
internal/kafka/internal/clusters/provider_moq.go
internal/kafka/internal/clusters/standalone_provider.go
internal/kafka/internal/clusters/standalone_provider_test.go
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go
internal/kafka/test/integration/cluster_metrics_test.go
internal/kafka/test/integration/ocm_client_test.go
pkg/client/ocm/client.go
pkg/client/ocm/client_moq.go
pkg/client/ocm/client_test.go
pkg/metrics/metrics.go
test/mocks/api_server.go

Adds and exposes `kas_fleet_manager_cluster_provider_resource_quota_max_allowed` metric in the KAS Fleet Manager /metric endpoint. This provides information on the maximum allowed number of resources that can be consumed by the provided cluster provider user (i.e. ocm user). 
We only need to expose metrics for `ocm` cluster provider. OCM quota metrics will be set when the user provides ocm client credentials to the kfm service, either ocm clientid+secret or the token.
Standalone providers doesn't have any resource quota limits so no quota metrics will be exposed. 
Example metric: 
```
kas_fleet_manager_cluster_provider_resource_quota_max_allowed{quota_id="<quota-id>", provider="ocm"} 100
```
- Run kas fleet manager with ocm credentials specified
- Curl http://localhost:8080/metrics
- …

feat: add cluster_provider_resource_quota_max_allowed metric

---

cmd/kas-fleet-manager/main_test.go
internal/kafka/internal/config/dataplane_cluster_config.go
internal/kafka/internal/migrations/20220829200000_dynamic_scale_down_worker_to_leader_leases.go
internal/kafka/internal/migrations/migrations.go
internal/kafka/internal/services/clusters.go
internal/kafka/internal/workers/cluster_mgrs/cleanup_clusters_mgr_test.go
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go
internal/kafka/internal/workers/cluster_mgrs/deprovisioning_clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/deprovisioning_clusters_mgr_test.go
internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_down_mgr.go
internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_down_mgr_test.go
internal/kafka/internal/workers/cluster_mgrs/dynamic_scaleup_mgr.go
internal/kafka/providers.go
internal/kafka/test/helper.go
internal/kafka/test/integration/cluster_mgr_test.go

This PR adds the dynamic scale down manager.
It's implementation is heavily influenced by the DynamicScaleUpManager design. 
Additionally, the dynamic scale down evaluator re-uses the dynamic scale up evaluation when evaluating for the below conditions: 
```
* There is at least a cluster in the provider's region that has enough capacity to allocate
the biggest instance size of the instance types supported by the empty cluster
* There will be free capacity (in streaming units) for each instance type supported by the cluster in
the provider's region that is smaller or equal than the defined slack capacity (also in streaming units) of the given instance type. 
Free capacity is defined as max(total) capacity - consumed capacity.
For the calculation of the max capacity:
* Clusters in …
```

Add scale down manager

---

.golangci.yml

golangci-lint 'scopelint' filter is deprecated. This replaces
the 'scopelint' linter by the 'exportloopref' as indicated
by golangci-lint.
Run the linter locally with `make lint`. Verify no errors are shown.

feat: replace scopelint linter by exportloopref

---

pkg/client/observatorium/api.go

Current error seen in Sentry only shows the metrics that failed to be fetched, e.g.
```
KAFKAS-MGMT-9: failed to retrieve metrics
caused by: Failed to fetch metrics data [{__name__=~'kafka_namespace:haproxy_server_bytes_in_total:rate5m|kafka_namespace:haproxy_server_bytes_out_total:rate5m', exported_namespace=~'<namespace>'}]
```
We should also show the error message for each metric to help debug issues around metric collection.

feat: show error message on metric fetch failure

---

internal/kafka/test/integration/cluster_mgr_test.go

Add checks for the created machine pool when running in non emulated mode.
Closes Closes https://issues.redhat.com/browse/MGDSTRM-9697
NB: The PR is opened as draft to test this first. 
The added checks should pass
```
OCM_ENV=development TEST_SUMMARY_FORMAT=standard-verbose  make test/integration/kafka TESTFLAGS="-run TestClusterManager_SuccessfulReconcile"
```
- ~~[ ] CI and all relevant tests are passing~~

test(cluster_mgr): add missing machinepool verification integration tests

---

internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_up_mgr.go
internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_up_mgr_test.go

ensure that clusters in deleting state are skipped during capacity evaluation
Clusters in 'deprovisiong' and 'cleanup' state can't accept kafka anymore. We shouldn't consider them as clusters that contribute to free streaming units nor as clusters that are capable of accepting the biggest instance size capcity. The clusters in these states should be skipped from any capacity evaluation consideration
Added unit test should pass

fix(dynamic_scale_up): ensure that clusters in deleting state are skipped during capacity evaluation

---

internal/connector/test/integration/features/connector-api.feature
internal/kafka/internal/api/public/api/openapi.yaml
internal/kafka/internal/api/public/model_version_metadata.go
internal/kafka/test/integration/kafka/features/kafka-api.feature
internal/kafka/test/integration/metadata_test.go
openapi/kas-fleet-manager.yaml
pkg/api/metadata.go
pkg/api/metadata_types.go

(https://issues.redhat.com/browse/MGDSTRM-9585)
1. run ` make run ` from the root
2. run ` curl -H "Authorization: Bearer $(ocm token)" http://localhost:8000/api/kafkas_mgmt/v1 | jq . `

feat: expose the fleet manager version

---

Dockerfile

This follows up on https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1321, notably https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1321#issuecomment-1263717395

build(dockerfile): ensure that docker in installed so that commitsha is read during build

---

internal/kafka/constants/kafka.go
internal/kafka/internal/api/admin/private/api/openapi.yaml
internal/kafka/internal/api/admin/private/model_kafka_update_request.go
internal/kafka/internal/api/private/api/openapi.yaml
internal/kafka/internal/api/private/model_managed_kafka_all_of_metadata_labels.go
internal/kafka/internal/handlers/admin_kafka.go
internal/kafka/internal/handlers/admin_kafka_test.go
internal/kafka/internal/handlers/validation.go
internal/kafka/internal/handlers/validation_test.go
internal/kafka/internal/presenters/managedkafka.go
internal/kafka/internal/services/kafka.go
internal/kafka/test/integration/admin_kafka_test.go
internal/kafka/test/integration/data_plane_endpoints_test.go
openapi/kas-fleet-manager-private-admin.yaml
openapi/kas-fleet-manager-private.yaml
pkg/api/managedkafkas.managedkafka.bf2.org/v1/types.go

feat: add handling of suspended field in admin api patch kafka
CI passing and states changing as per epic brief for kafka suspension

feat: add handling of suspended field in admin api patch kafka

---

internal/kafka/constants/kafka.go
internal/kafka/internal/handlers/admin_kafka.go
internal/kafka/internal/handlers/admin_kafka_test.go
internal/kafka/internal/services/data_plane_kafka.go
internal/kafka/internal/services/data_plane_kafka_test.go
internal/kafka/test/integration/admin_kafka_suspension_test.go
internal/kafka/test/integration/admin_kafka_test.go
internal/kafka/test/mocks/kasfleetshardsync/kas-fleetshard-sync.go

The Fleetshard Operator will have a new status to report called 'Suspended'. Fleetshard will report this status by setting the ManagedKafka CR 'Ready' condition to have the following values: `Status=False,Reason=Suspended`.
On top of that, there are also two new KafkaRequest status set in KAS Fleet Manager (as seen in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1344)
* `resuming`: set by a user to indicate that they want to resume their Kafka instance from a `suspended` or `suspending` state.
* `suspending`: set by a user to indicate that they want to suspend their Kafka instance. This can only be updated from a `ready` state.
All three new statuses must be accommodated for when processing real Kafka deployments when the Fleetshard calls the …

feat: set suspended status reported by fleetshard

---

internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
pkg/client/aws/client.go

When kafka instances are created from cloud providers different than AWS, AWS Route 53 is also used to create DNS entries when kafka external names are enabled. Before this PR the AWS client was instantiated using a region value obtained from the kafka request being managed. The issue with that approach is that kafka instances allocated in cloud providers different than AWS, for example GCP, have different region names, which don't exist in AWS.
This changes the logic of the methods that make use of Route53 to make sure a valid AWS region is specified, no matter the cloud provider of the kafka instance being managed.
We define a AWS Route53 region for each cloud provider, independently on the cloud provider's region where the kafka is allocated. This is acceptable due to most Route53 …

feat: set route53 regional endpoints per cloud provider

---

internal/kafka/internal/config/dataplane_cluster_config.go
internal/kafka/test/integration/admin_kafka_test.go
internal/kafka/test/integration/cloudprovider_test.go
internal/kafka/test/integration/cluster_metrics_test.go
internal/kafka/test/integration/cluster_mgr_test.go
internal/kafka/test/integration/cluster_service_test.go
internal/kafka/test/integration/data_plane_endpoints_test.go
internal/kafka/test/integration/kafka_create_test.go
internal/kafka/test/integration/kafkas_test.go
internal/kafka/test/integration/require_terms_acceptance_middleware_test.go

Related to https://issues.redhat.com/browse/MGDSTRM-7819. 
This reduce calls to sso from 23 to only 1 call to provision fleetshard service account. The
improvement should be of the same margin for the provisioning of a ClientID used to setup cluster
IDP configuration.
*Note:* The PR is only concerned about offering an improvement on fleetshard service account creation and cluster IDP clientID creation.

Reduce number of calls made from integration test to the SSO service

---

internal/kafka/test/integration/admin_kafka_test.go

set the reconciliation interval to 1m to delay the kafka deletion process so that we can test kafka in 'deprovision'
and 'deleting' state without them being deleted before our test is run.
This avoid some randomly failures where the Kafka under test will be reported as not found.

test(integration): harden the TestAdminKafka_Update test

---

internal/kafka/internal/config/kafka_supported_instance_types.go
internal/kafka/internal/config/kafka_supported_instance_types_test.go

To allow seamless rollout of the kafka supported_billing_models https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1371 into our saas environments.
This allows us to avoid a complex rollout procedure described in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1371#issuecomment-1302070076.
After next week's prod rollout the changes in here should be reverted.
Remove the `supported_billing_models` subsection appearances in the `config/kafka-instance-types-configuration.yaml`. Then run kas-fleet-manager serve. Observe how it starts correctly now as opposed to before the PR.

chore: temporarily remove mandatory kafka supported_billing_models

---

Makefile

Fix mermaid diagrams generation makefile task failing to run due to permission issues because of the user running in the container having different id than the ownership and permissions of the directories and their contents mounted as shared volumes from the host
Run `make docs/generate/mermaid` and verify no errors are shown

fix: fix mermaid diagrams generation

---

internal/kafka/internal/api/dbapi/kafka_request_types.go
internal/kafka/internal/migrations/20221109140000_add_desired_kafka_billing_model.go
internal/kafka/internal/migrations/20221109150000_rename_kafka_billing_model_column.go
internal/kafka/internal/migrations/migrations.go
internal/kafka/internal/presenters/kafka.go
internal/kafka/internal/presenters/kafka_test.go
internal/kafka/internal/services/quota/ams_quota_service.go
internal/kafka/internal/services/quota/ams_quota_service_test.go
internal/kafka/test/mocks/kafkas/kafkas.go

Related to https://issues.redhat.com/browse/MGDSTRM-10006.
As part of the long-lived eval instances functionality a long-lived eval instance will be able to be promoted to a non-eval instance. Due to this, we need to keep track of both the desired and actual kafka billing models being used, as they might not be in-sync at all times.
This PR performs two main changes:
1. A new column `desired_kafka_billing_model` is added to the kafka request DB type
2. The column `billing_model` is renamed to `actual_kafka_billing_model`
DB migrations have been included to transition from the old to the new columns model.
This PR does not perform any changes at openapi definition level as those are not strictly needed. If we deem we want to perform any modification at that level another PR will be opened …

Add kafka desired and existing billingmodel

---

internal/kafka/internal/services/clusters.go
internal/kafka/internal/services/data_plane_cluster.go
internal/kafka/internal/services/data_plane_kafka.go
internal/kafka/internal/services/data_plane_kafka_test.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/kafkaservice_moq.go
internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/preparing_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/preparing_kafkas_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/ready_kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/ready_kafkas_mgr_test.go
internal/kafka/test/common/kafka_pollers.go
internal/kafka/test/integration/cluster_mgr_test.go
internal/kafka/test/integration/data_plane_endpoints_test.go
internal/kafka/test/integration/kafka_create_test.go
internal/kafka/test/integration/kafkas_test.go
internal/kafka/test/integration/observatorium_test.go
pkg/metrics/metrics.go

In our codebase we had several naming issues when referencing the `github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/internal/kafka/constants`:
* In some places that package was imported with an alias `constants2` which was not needed
* In some places that package was imported with an alias `constants2` at the same time as another import without the package alias in the same file
This PR normalizes the import naming for those cases so the `constants2` package alias is not used anymore.
Verify there are no references to `constants2` in our codebase

refactor: fix naming issues with kafka internal constants package

---

internal/connector/internal/config/connectors.go
internal/connector/internal/config/connectors_test.go
internal/connector/test/bad-connector-metadata/bad-connector-metadata.yaml
internal/connector/test/integration/connector-metadata/aws-sqs-source-v1alpha1-metadata.yaml
internal/connector/test/integration/connector-metadata/log_sink_0.1_metadata.yaml
internal/connector/test/integration/feature_test.go
internal/connector/test/missing-connector-metadata/log_sink_0.1_metadata.yaml
internal/connector/test/unknown-connector-metadata/aws-sqs-source-v1alpha1-metadata.yaml
internal/connector/test/unknown-connector-metadata/log_sink_0.1_metadata.yaml

Load connectors metadata from flat yaml config files instead of pushing it upstream in connector catalog projects.
CI tests should pass.

feat(connectors): fixes MGDCTRS-1635, support for loading connectors metadata from yaml config files

---

internal/kafka/internal/services/clusters.go
internal/kafka/internal/services/clusters_test.go
internal/kafka/internal/services/clusterservice_moq.go
internal/kafka/internal/workers/cluster_mgrs/deprovisioning_clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/deprovisioning_clusters_mgr_test.go

Acronyms/Initialisms should have a consistent case
Tests pass

refactor: rename cluster service FindNonEmptyClusterById initialism

---

config/quota-management-list-configuration.yaml
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/quota.go
internal/kafka/internal/services/quota/ams_quota_service.go
internal/kafka/internal/services/quota/ams_quota_service_test.go
internal/kafka/internal/services/quota/quota_management_list_service.go
internal/kafka/internal/services/quota/quota_management_list_service_test.go
internal/kafka/internal/services/quotaservice_moq.go
internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr_test.go
internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr_test.go
internal/kafka/test/integration/kafkas_test.go
pkg/quota_management/account.go
pkg/quota_management/account_test.go
pkg/quota_management/billing_model.go
pkg/quota_management/organisation.go
pkg/quota_management/organisation_test.go
pkg/quota_management/quota.go
pkg/quota_management/quota_management_list.go
pkg/quota_management/quota_management_list_test.go
pkg/quota_management/shared.go

Added support for KFM billing model to quota-list so that different billing model are supported for the same instance type (standard, eval, marketplace, ...)
1) Run KFM locally with QUOTA-LIST and the specified configuration file. Try to create kafkas and check that it gives an error after reaching the quota.
2) Try to create a kafka with a user not listed in the QUOTA-LIST (set any_user to false) and ensure it allows you to create only one developer instance.
3) Run KFM locally with  AMS and check that it still works as before
**Example configuration file**
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/bde4796f5700b99671e532ac008d4c8be039c1fd/config/quota-management-list-configuration.yaml

feat: Added support for KFM Billing Models to QUOTA-LIST

---

internal/kafka/constants/kafka.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/test/integration/admin_kafka_suspension_test.go
pkg/metrics/metrics.go

feat: set current kafka status to 1 and others to 0 for kafka_requests_current_status_info metric

feat: set current kafka status to 1 and others to 0 for kafka_requests_current_status_info metric

---

internal/kafka/internal/api/dbapi/kafka_request_types.go
internal/kafka/internal/migrations/20221129121515_add_expires_at_to_kafka_request.go
internal/kafka/internal/migrations/migrations.go

Adds an `expires_at` column which contains the timestamp of when a Kafka instance is scheduled to expire. On expiration, Kafka instances will be marked for deletion by having its status set to 'deprovision'. 
`expires_at` should only be set for Kafka instances that have a limited lifespan (i.e. `developer` and `eval` instances). This field should not be set for `standard` instances as these should never expire. 
Related JIRA issue: [MGDSTRM-10010](https://issues.redhat.com/browse/MGDSTRM-10010)
Run `make db/migration`
Login to the database using `make db/login`

feat: add expires_at column to the kafka_requests table

---

internal/kafka/internal/migrations/20221216120000_remove_wrongly_created_enterprise_cluster.go
internal/kafka/internal/migrations/migrations.go

I accidentally hit the enterprise cluster registration endpoint in prod. This migration removes the cluster from the database.
1. Check the KAS Fleet Manager Metrics dashboard in grafana prod and make sure that the cluster stuck in waiting for fleetshard operator is removed.

fix: remove wrongly created enterprise cluster in prod

---

go.mod
pkg/quota_management/expiration_date_test.go

In PR https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1433 The usage of `gopkg.in/yaml.v3` was introduced. This added the usage of `gopkg.in/yaml.v2` and `gopkg.in/yaml.v3` depending on the package in the repository unnecessarily.
This PR removes the usage of `gopkg.in/yaml.v3` to unify the `gopkg.in/yaml` library version used
There are no references to `gopkg.in/yaml.v3` in the repository.

chore: Use gopkg.in/yaml.v2 instead of v3

---

internal/kafka/internal/handlers/kafka.go
internal/kafka/internal/handlers/validation.go
internal/kafka/internal/handlers/validation_test.go

Related to https://issues.redhat.com/browse/MGDSTRM-10014.
This PR updates the kafka billing models validation in the kafka create endpoint. The set of valid values is now gathered from the configured supported kafka billing models in `config/kafka-instance-types-configuration.yaml`.

feat: validate kafka billing models in kafka creation from instance types config

---

.github/workflows/ci.yaml

To fix deprecation and future removal message around usage of the save-state and set-output GitHub action commands. See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for details.
Verify that the `Cache go module` GitHub CI action step does not show any warning.

chore: upgrade GitHub action actions/cache to v3

---

pkg/client/aws/client.go
pkg/client/aws/client_test.go

Replace the appearance of the `InvalidChangeBatch` magic string by the usage of a constant available in the AWS Go Client library
Tests pass

refactor: replace route53 invalidchangebatch magic number to constant

---

internal/kafka/internal/api/dbapi/kafka_request_types.go
internal/kafka/internal/migrations/20230109140000_update_expires_at_zero_value.go
internal/kafka/internal/migrations/migrations.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/internal/services/kafkaservice_moq.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go
internal/kafka/test/integration/kafkas_test.go
internal/kafka/test/mocks/kafkas/kafkas.go

Related to https://issues.redhat.com/browse/MGDSTRM-10012
This PR adds logic that takes care of marking long lived eval instances whose expiration (ExpiresAt) has been reached as deprovisioning.
The PR assumes that for developer instances the ExpiredAt column is also set. The code for that is still not implemented but merging this should not be an issue as this PR is to be merged against the `longlived-instances-featurebranch` and this PR and the one about setting ExpiredAt column for developer instances should both be merged together in main.
The logic for deprovisioning instances now evaluates whether kafka instances should be deprovisioned based on the ExpiresAt column, no matter the kafka instance type.
Additionally, the ExpiresAt type at DB type level has been changed from time.Time …

Add long lived eval instances expiration deletion logic

---

internal/kafka/internal/handlers/admin_kafka.go
internal/kafka/internal/handlers/admin_kafka_test.go
internal/kafka/internal/routes/route_loader.go
internal/kafka/test/integration/admin_kafka_suspension_test.go
internal/kafka/test/integration/admin_kafka_test.go

Related to https://issues.redhat.com/browse/MGDSTRM-10230.
This PR adds logic to ensure Kafka instances that are in grace period cannot be resumed when the kafka admin update endpoint is called.
It also adds validation for when resuming is performed, as until now any state was accepted.
To do:
1. Tests pass
2. Validate that only instances on `suspended` status can be resumed
2.1 Validate that a suspended instance with expiration date set and within  the grace period period cannot be resumed
2.2 Validate that a suspended instance with expiration date set that has yet not reached grace period can be resumed
2.3 Validate that a suspended instance without expiration date set can be resumed, no matter the configuration of grace period days

Prevent resuming of kafka instances in grace period

---

internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go

Related to https://issues.redhat.com/browse/MGDSTRM-10249.
As part of the design of the long lived eval instances functionality and as implemented in https://issues.redhat.com/browse/MGDSTRM-10012 it was decided that the logic that verifies whether a kafka instance should be marked for provisioning due to reaching its expiration date should make use of the `expires_at` value in the DB. This applies to all instance types including developer instances, where up until now had calculated its expiration time dynamically from the config and not being persisted in the database.
This PR adds logic to set the expires_at DB field to created_at + configured lifespanSeconds when creating kafka instances whose corresponding instance size has a configured lifespanSeconds set. 
TODO:
1. Tests pass
1. …

Set expires_at on kafka creation when lifespanSeconds configuration is defined

---

internal/connector/internal/services/connector_types.go
internal/connector/test/integration/features/connector-api.feature

Added support for matching multiple connector type labels using like instead of and operator
CI tests including new integration tests MUST pass.

fix(connectors): fixes MGDCTRS-1851, added support for matching multiple connector type labels using like instead of and operator

---

internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go

Reconcile the SyncSet for Enterprise clusters using ocm. Compared to managed clusters, the SyncSet will only contain the Observability and Pull Secret pieces.
1. Register an enterprise cluster
2. Make sure that it reaches 'ready' status and that only the SyncSet is reconciled.
3. Make sure that the Observability Operator is running on the cluster.
4. Step 3 also ensures that the Pull Secrets have been installed.

feat: reconcile syncset for enterprise clusters

---

internal/kafka/internal/presenters/kafka.go
internal/kafka/internal/presenters/kafka_test.go

Related to https://issues.redhat.com/browse/MGDSTRM-10247
With the introduction of long lived eval instances now the expiration date of a kafka instance (if set) is stored in the database. Specifically, from the kafka_requests table, expires_at column.
This PR updates the kafka presenter to retrieve the expires_at value from the database independently of the kafka instance type
1. Verify that when creating developer instances the expires_at is correctly set when calling kafka get endpoint. Then modify the lifespanSeconds config for developer instances to a different value and restart KFM. Finally call again the kafka get endpoint and verify that expires_at has not changed for the already existing kafka instance
2. Verify that when creating a standard instance expires_at is not returned as …

feat: present kafka request's expires_at from database

---

internal/kafka/constants/metrics.go
internal/kafka/internal/presenters/metric.go
internal/kafka/internal/presenters/metric_test.go
pkg/client/observatorium/api.go

Two new Prometheus metrics gathered from Observatorium are exposed in KFM:
- kas_topic_partition_log_size_bytes: Size in bytes of each topic partition on each kafka broker
- kas_broker_partition_log_size_bytes_top50: Sizes in bytes of the top 50 topic partitions for each kafka broker
This new metrics have some useful labels that were still not whitelisted in KFM. This commit also whitelists in KFM the following labels:
- partition_id
- topic_id (a new name for the old 'topic' label that follows our label naming conventions)
This new whitelisted metric labels apply automatically to all already existing metrics too
1. Run KFM and a data plane and wait until the data plane is ready
2. Create a kafka instance
3. Create a kafka topic in that kafka instance using rhoas cli
4. Verify that the …

feat: add kafka log size metrics to KFM metrics endpoints

---

internal/connector/internal/services/connector_types.go
internal/connector/test/integration/feature_test.go

Remove labels for deleted connector types from labels query API
Added an old label in integration tests, which should be ignored and current labels query tests should not be affected. 

fix(connectors): fixes MGDCTRS-1880, remove labels for deleted connector types from labels query API

---

config/dynamic-scaling-configuration.yaml
internal/kafka/internal/config/dynamic_scaling_config.go

The Fleetshard Operator addon is currently incompatible with OpenShift 4.12. See https://issues.redhat.com/browse/MGDSTRM-10450 for further information.
This is a temporary change to ensure that our nightly tests do not fail on Fleetshard Operator addon installation.
The `NewDataPlaneOpenShiftVersion` configuration is used to define the OpenShift version assigned by the ClusterBuilder when creating new data plane clusters (see [here](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/9305f1b82d8ce30bcb6e23afd8daccb79d2e811d/internal/kafka/internal/clusters/cluster_builder.go#L70))
Once the issue is resolved, we can reset this back to an empty string so that KAS Fleet Manager can provision data plane clusters with the latest version.
OpenShift 4.11.22 is the latest version of …

feat: set data plane openshift version to 4.11.22

---

internal/kafka/constants/cluster.go
internal/kafka/internal/api/public/api/openapi.yaml
internal/kafka/internal/api/public/api_enterprise_dataplane_clusters.go
internal/kafka/internal/clusters/ocm_provider.go
internal/kafka/internal/clusters/provider.go
internal/kafka/internal/clusters/provider_moq.go
internal/kafka/internal/clusters/standalone_provider.go
internal/kafka/internal/handlers/cluster.go
internal/kafka/internal/handlers/cluster_test.go
internal/kafka/internal/handlers/validation.go
internal/kafka/internal/handlers/validation_test.go
internal/kafka/internal/services/clusters.go
internal/kafka/internal/services/clusterservice_moq.go
internal/kafka/internal/workers/cluster_mgrs/cleanup_clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/cleanup_clusters_mgr_test.go
internal/kafka/internal/workers/cluster_mgrs/deprovisioning_clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/deprovisioning_clusters_mgr_test.go
internal/kafka/test/integration/cluster_deregistration_endpoint_test.go
openapi/kas-fleet-manager.yaml

Implements the deregistration of an Enterprise cluster. The SyncSet is removed and the cluster is soft-deleted afterwards.
1. Create an OCM cluster
2. Run the KFM locally, but don't target this cluster
3. Register the cluster using the enterprise registration endpoint
4. Make sure that registration was successful and that the Observability resources have been created
5. Deregister the cluster by calling the deregistration endpoint
6. Make sure that the Observability resources are removed, the cluster only soft deleted in the database.

feat: cluster deregistration

---

internal/kafka/internal/api/admin/private/api/openapi.yaml
internal/kafka/internal/api/admin/private/model_list.go
internal/kafka/internal/api/public/api/openapi.yaml
internal/kafka/internal/api/public/model_list.go
openapi/kas-fleet-manager-private-admin.yaml
openapi/kas-fleet-manager.yaml

According to this open issue: https://github.com/OAI/OpenAPI-Specification/issues/3069
Overriding properties seems to be an undefined behavior, I found this edge case used here and I'm proposing a possible, retrocompatible fix.
The same fix has been applied in similar circumstances:
https://github.com/bf2fc6cc711aee1a0c2a/srs-fleet-manager/pull/326
(BTW, found generating a client using Kiota.)

Avoid overriding properties in OpenAPI Spec

---

.gitignore
Makefile
README.md
docs/feature-flags.md
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go
internal/kafka/providers.go
pkg/client/observatorium/observability_config.go
pkg/client/observatorium/observability_config_test.go
secrets/observability-cloudwatchlogs-config.yaml.sample
templates/secrets-template.yml
templates/service-template.yml

Related to https://issues.redhat.com/browse/MGDSTRM-10270.
This PR adds support in KFM to enable configuration of CloudWatch Logs credentials for Observability on the data plane side.
Two flags are added to control this functionality:
* `--observability-cloudwatchlogging-enable`: `Enable Observability to deliver logs to AWS CloudWatch`. Default value: false
* `--observability-cloudwatchlogging-config-file-path`: Path to a file containing the configuration for Observability related to AWS CloudWatch Logging in YAML format. Only takes effect when `--observability-cloudwatchlogging-enable` is set. Default value: `secrets/observability-cloudwatchlogs-config.yaml`
When the functionality is enabled through the enable flag a K8s secret is created on the Data Plane side for all Data Plane …

feat: add configurable Observability CloudWatch Logs functionality

---

internal/kafka/constants/kafka.go
internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafkaservice_moq.go
internal/kafka/internal/services/quota.go
internal/kafka/internal/services/quota/ams_quota_service.go
internal/kafka/internal/services/quota/ams_quota_service_test.go
internal/kafka/internal/services/quota/quota_management_list_service.go
internal/kafka/internal/services/quota/quota_management_list_service_test.go
internal/kafka/internal/services/quotaservice_moq.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go
pkg/client/ocm/client.go
pkg/client/ocm/types.go
pkg/quota_management/account.go
pkg/quota_management/organisation.go

The following changes adds logic to reconcile the `expires_at` value of Kafka instances in KFM.
The `expires_at` value determines when a Kafka instance is to expire, marked for deletion. It can either contain a timestamp, of when the Kafka instance will be marked for deletion, or null which means the Kafka instance will never expire.
The value is determined whether LifespanSeconds in the Kafka instance types configuration is defined for that instance type. If LifespanSeconds is defined, the value should be calculated with `Kafka.CreatedAt + LifespanSeconds`. 
If it's not defined, then the value is based on whether the organisation/user has an active subscription (SKU allowance given to the org) for the particular billing model used by the Kafka instance. We can't get information on the …

feat: reconcile expires at value for kafka instances

---

internal/kafka/internal/api/public/api/openapi.yaml
internal/kafka/internal/api/public/api_security.go
openapi/kas-fleet-manager.yaml

Generating a client SDK using [Kiota](https://github.com/microsoft/kiota) I found this little inconsistency.
Looking at the rest of the specification seems like `$ref: '#/components/schemas/Error'` is used everywhere but in those two cases left.
I'm not sure if this was done intentionally, but the `example` section is consistent with this proposed change.

Specify the Error schema ref instead of a generic empty object

---

internal/kafka/internal/services/quota/ams_quota_service.go
internal/kafka/internal/services/quota/ams_quota_service_test.go
internal/kafka/internal/services/quota/internal/mocks/ams/subscriptions_mock.go
internal/kafka/internal/services/quota/quota_management_list_service.go
internal/kafka/internal/services/quota/quota_management_list_service_test.go
pkg/client/ocm/client.go
pkg/client/ocm/client_moq.go

we are getting a 403 error when we try to access the reserved_resources of certain subscriptions. After some discussion, fixing that permission error is not trivial, so we discussed an alternative implementation that won't involve reserved_resources.
This commit implements that solution: take the billing model from the `cluster_billing_model` of the subscription.
Another change is the way we detect if a subscription for a cluster already exists: after some discussion with the AMS team, we discovered that we couldn't have more than one subscription with the same `cluster_id` value. That means we no longer need to check the reserved resources: if a subscription for a given cluster_id exists, then it is the subscription we are searching for.

fix: removed call to reserved_resources

---

internal/kafka/internal/services/kafka.go
internal/kafka/test/integration/kafka_create_test.go

An enterprise Kafka can only be created on an enterprise cluster. Previously, the cluster used in test will get reconciled and thus the capacity information being reset to an empty map because it was seen as a managed cluster.
Setting the cluster type appropriately so that the capacity information are always there and not reconciled.

test(integration): harden enterprise kafka creation test as only enterprise cluster should be used

---

internal/kafka/internal/api/public/api/openapi.yaml
internal/kafka/internal/api/public/model_enterprise_osd_cluster_payload.go
internal/kafka/internal/clusters/ocm_provider.go
internal/kafka/internal/clusters/ocm_provider_test.go
internal/kafka/internal/clusters/provider.go
internal/kafka/internal/clusters/provider_moq.go
internal/kafka/internal/clusters/standalone_provider.go
internal/kafka/internal/clusters/types/types.go
internal/kafka/internal/handlers/cluster.go
internal/kafka/internal/handlers/cluster_test.go
internal/kafka/internal/routes/route_loader.go
internal/kafka/internal/services/clusters.go
internal/kafka/internal/services/kas_fleetshard_operator_addon.go
internal/kafka/test/integration/cluster_deregistration_endpoint_test.go
internal/kafka/test/integration/cluster_registration_endpoint_test.go
openapi/kas-fleet-manager.yaml

feat: get additional cluster info from ocm during registration
NOTE.
there was one body parameter removed from the request. Normally deprecation policy should be followed, but this endpoint is not yet used by anybody (apart from RHOAS CLI - who are aware of this change). The removed external cluster ID is redundant and it was agreed that its better to remove it now rather than wait for people start using it and remove it later
tests should pass

feat: get additional cluster info from ocm during registration

---

internal/kafka/internal/services/data_plane_cluster.go
internal/kafka/internal/services/data_plane_cluster_test.go
internal/kafka/test/integration/cluster_registration_endpoint_test.go

Ensure that capacity information are always sent for enterprise kafkas
It is okay to remove the scaling type guard as when the scaling type is not "auto" - all non enterprise clusters will have their capacity information reset.

fix(enterprise): ensure that capacity information are always sent for enterprise kafkas

---

internal/kafka/internal/services/kafka.go

Logging in sentry when an OCM cluster is not ready is not needed when generating the reserved managed kafka instances list. It is a common occurrence that fleetshard calls the endpoint in KFM and not considered an issue. Therefore we change the log level of that scenario to a debug level log.

feat: change log level logging when cluster not ready in genreservedkafkas

---

internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafkaservice_moq.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go

It was temporarily needed until long-lived instances code was rolled out. Not needed anymore.
This temporary migration was introduced in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1471/, part of https://issues.redhat.com/browse/MGDSTRM-10012
Tests pass

feat: remove temporary expires_at migration logic in the kafka_mgr reconciler

---

internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go
internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go

Remove the logic in the kafkas_mgr that took care of setting the expires_at DB attribute for kafka instances whose size had lifespanSeconds defined and the expires_at DB attribute value to the zero-value of time.Time.
It was temporarily needed until the long-lived instances code was rolled out. It is Not needed anymore as now new kafka instances whose size has lifespanSeconds should always have the expires_at field set on creation time.
This temporary migration was introduced in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1499, part of https://issues.redhat.com/browse/MGDSTRM-10201.
Tests pass

feat: remove temporary expires_at migration logic for lifespan based instances

---

internal/kafka/internal/config/dataplane_cluster_config.go
internal/kafka/internal/config/dataplane_cluster_config_test.go
internal/kafka/internal/handlers/cluster_test.go
internal/kafka/internal/handlers/validation.go
internal/kafka/internal/handlers/validation_test.go
internal/kafka/internal/services/cluster_placement_strategy.go
internal/kafka/internal/services/cluster_placement_strategy_test.go
internal/kafka/internal/services/clusters.go
internal/kafka/internal/services/clusters_test.go
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go
internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go
internal/kafka/test/integration/cluster_service_test.go
internal/kafka/test/integration/kafka_create_test.go

enterprise clusters should be ignored when checking for manual list placement when a non enterprise kafkas is created
A normal standard kafka can only get scheduled on managed clusters and not enterprise one.
This consideration has to be taken into account for both auto & manual scaling modes.
rename ResKafkaInstanceCount struct field from "Clusterid" to "ClusterID"
The added integration & unit test for the first commit should pass.

fix: enterprise clusters should be ignored when checking for manual list placement when creating a normal Kafkas

---

docs/deploying-kas-fleet-manager-to-openshift.md
templates/db-template.yml
templates/service-template.yml

It has been detected that starting from OCP 4.11 when KFM K8s Deployment is deployed the following warnings are shown:
```
serviceaccount/kas-fleet-manager configured
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (containers "migration", "service", "envoy-sidecar" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "migration", "service", "envoy-sidecar" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "migration", "service", "envoy-sidecar" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "migration", "service", "envoy-sidecar" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost") …
```

feat: set restrictive security contexts in KFM deployments

---

templates/service-template.yml

Indentation was wrong
Template is deployed and the pod runs and gets ready even if the secret does not exist (assuming cloudwatchlogs flag is disabled)

fix: fix dataplane cloudwatchlogs secret being optional at template level

---

internal/kafka/internal/handlers/cluster_test.go
internal/kafka/internal/presenters/cluster.go
internal/kafka/internal/presenters/cluster_test.go
internal/kafka/test/integration/cluster_get_enterprise_test.go

Return all instance sizes for Enterprise clusters, regardless of capacity.

feat: return all sizes regardless of capacity for enterprise

---

Makefile
docs/deploying-observability-remote-write-proxy-in-openshift.md
templates/observability-remote-write-proxy-oidc-secret.yml
templates/observability-remote-write-proxy-route.yml
templates/observability-remote-write-proxy.yml

Related to https://issues.redhat.com/browse/MGDSTRM-10333.
This PR adds the OCP templates needed to deploy [Observability Remote Write Proxy](https://github.com/bf2fc6cc711aee1a0c2a/observability-remote-write-proxy).
The aim of Observability Remote Write Proxy in KAS Fleet Manager context is for the managed kafka related Prometheus metrics in the Data Planes to be sent to Observatorium indirectly through the proxy.
The motivation of sending the credentials indirectly through the proxy is to avoid needing to store Observatorium credentials in the Data Planes themselves.
This PR adds the following OCP templates:
* `templates/observability-remote-write-proxy-oidc-secret.yml`: Contains the needed K8s secret when OIDC token retrieval is enabled in Observability Remote Write Proxy.
* …

feat: add observability proxy deployment

---

templates/envoy-config-configmap.yml

This PR disables rate limiting in the Envoy config for requests that start with the URL Path `/api/kafkas_mgmt/v1/obs-proxy-verification/`.
This modifies the development template. Additional changes will be needed for the Envoy configurations in the Stage and Prod environments.
It has been decided that no rate limit will be applied to that path prefix because we don't want to be rate limited on those URLs, similarly to what was done for the agent-clusters endpoints.

feat: disable rate limiting for obs-proxy-verification endpoint

---

templates/observability-remote-write-proxy-route.yml
templates/route-template.yml

It was defined in both the .name and the .metadata.name attributes in the template and that is redundant.
Also renamed the ocp routes template names to reflect more accurately what the templates contain.

chore: remove ocp route templates redundant name attribute

---

internal/kafka/internal/services/clusters.go
internal/kafka/test/common/cluster_pollers.go
internal/kafka/test/common/poll.go

Added additional logs to help debug issues with failing tests due to unmatched external ids. See related JIRA issue for more details: https://issues.redhat.com/browse/MGDSTRM-10826
1. Ensure PR checks passes
2. Verify that the TestClusterManager_SuccessfulReconcile has additional logs that shows the external_id of data plane clusters when waiting for cluster id assignment and for the status to reach a certain state.

test: log cluster external id in cluster pollers

---

Makefile

When running any of the image build make targets on an M1 MacOS, it fails with the following error: 
```
=> [builder 7/9] COPY . ./                                                                                                                                                                                                                                                         0.2s 
=> ERROR [builder 8/9] RUN go mod vendor                                                                                                                                                                                                                                           0.2s 
------ …
```

fix: ensure image can be built on m1 macos

---

internal/kafka/internal/services/kafkatlscertmgmt/kafka_tls_certificate_management_service.go

Wait for dns propagation when the DNS resolver challenge is being performed to avoid errors like:
```
authorization failed: HTTP 400 urn:ietf:params:acme:error:dns - DNS problem: NXDOMAIN looking up TXT for _acme-challenge.cg3nrilq873kpludqfug.kafka.bf2.dev - check that a DNS record exists for this domain (ca=https://acme-v02.api.letsencrypt.org/directory)
```
which might occur if the dns are not propagated.

fix(certs): wait for dns propagation when the DNS resolver challenge is being performed

---

internal/kafka/internal/handlers/cluster.go

Do not perform nilness check on cluster spec as it is not needed
The `GetClusterSpec(clusterID string) (types.ClusterSpec, error)` will never return a nil ClusterSpec as it doesn't return the pointer.

fix: do not perform nilness check on cluster spec as it is not needed

---

internal/connector/internal/handlers/connector_agent.go
internal/connector/test/integration/feature_test.go
internal/kafka/test/integration/kafka/kafka_test.go
test/helper.go

Fixes https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1314#issuecomment-1322325692
1. Run integration tests twice without tearing down the database.

Ensure deferred functions are executed before Go runtime exits

---

internal/kafka/internal/services/kafkatlscertmgmt/kafka_tls_certificate_management_service.go
internal/kafka/internal/services/kafkatlscertmgmt/secure_storage.go

1. use the in memory storage constructor
2. apply the prefix filter when constructing the filter value for listing keys in aws secret manager

Minor reviews cert storage

---

internal/connector/internal/api/public/api/openapi.yaml
internal/connector/internal/api/public/api_connectors.go
internal/connector/internal/handlers/connectors.go
internal/connector/internal/handlers/connectors_test.go
internal/connector/test/integration/features/connector-api.feature
openapi/connector_mgmt.yaml

See https://issues.redhat.com/browse/MGDCTRS-1085
This PR reports HTTP409 (conflict) should the User try to patch an immutable property.
1. Create a Connector.
2. Try to patch an immutable property.
3. `HTTP409` / `CONNECTOR-MGMT-21: An attempt was made to modify an immutable field. Immutable fields are: Name, Kafka and SchemaRegistry.` error should be received (it used to be `HTTP200`). 
@kelvah @dhirajsb Do you know if this will require a UI change?

MGDCTRS-1085: PATCH returns wrong HTTP response if payload is incorrect

---

Dockerfile
Makefile

This reverts commit 00b9abe4d7694dbeecec6d8965db4de6aceb1464 which was introduced in the https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1635 PR. As mentioned in that PR itself it might be that some of the runners that perform image building might not have the needed docker version that already integrates BuildKit. That's exactly what happend in the runner we have in GitHub actions to build the main kfm image. See: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/actions/runs/4435378678/jobs/7783186399.
That's why this PR reverts it.

Revert "feat: make Dockerfile's go binary release download multiplaform"

---

.github/workflows/ci.yaml

actions/setup-go v4 enables dependency and build output caching by default. This changeset also removes the explicit run of the actions/cache GitHub action, as it is now performed by the actions/setup-go v4 GitHub action.
Caching can be observed in the GitHub action log

feat: update actions/setup-go GitHub action to v4

---

internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go
internal/kafka/test/integration/cloudprovider_test.go

Enterprise cluster don't eat up regions capacity and in that regard they should be omitted when we check if region's limits have been reached.
Unit & integration test should pass

fix(regions): ignore enterprise kafkas when checking for regions capacity

---

internal/kafka/internal/services/kafkatlscertmgmt/kafka_tls_certificate_management_service.go

The default logger is super chatty and doesn't conform to our log format. We already log cert management events, and the logger on the main certmagic client was disabled, so this just follows up on disabling logger on the acme issuer and the underlying client

refactor(certs): also disable the underlying acme client logger

---

internal/kafka/internal/services/data_plane_kafka.go
internal/kafka/internal/services/data_plane_kafka_test.go

Only allow transition to deleting state if the kafka was in deprovision state. 
This prevents erroneous attempts to delete a Kafka that has not been marked for deprovisioning

fix(data_plane_kafka): only allow transition to deleting state if the kafka was in deprovision state

---

internal/kafka/internal/services/kafkatlscertmgmt/kafka_tls_certificate_management_service.go

The LE prod instance is what we've configured by default.
If TestCA is not configure, the default letsencrypt Stage env was used which was causing an invalid account errors, like below:
```
https://acme-staging-v02.api.letsencrypt.org/acme/new-order: HTTP 400 urn:ietf:params:acme:error:malformed - KeyID header contained an invalid account URL: "https://acme-v02.api.letsencrypt.org/acme/acct/XXXXX"
```
Code review is enough

fix(cert): configure TestCA so that it points to Letsencrypt Prod instance as well

---

docker/Dockerfile_template
docker/Dockerfile_template_mocked
pr_check.sh

In https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1647 PR the Observability configuration was moved from its own flag and secret attribute to the data plane observability configuration file and being optional.
Now the Observability configuration is gathered from a container image by default instead of from a GitHub reference.
This PR removes references to the observability config github access token in the pr_check.sh and Dockerfile files used for midstream CI.

chore: remove observability config access token from CI files

---

docs/feature-flags.md
pkg/client/observatorium/client.go
pkg/client/observatorium/client_test.go
pkg/client/observatorium/config.go
pkg/client/observatorium/observability_config.go
templates/service-template.yml

The Observatorium debug flag is not used anywhere. This simplifies the set of flags and the logic for Observatorium configuration
* KAS Fleet Manager can be run
* Tests pass

chore: remove Observatorium debug flag

---

pkg/client/observatorium/client.go
pkg/client/observatorium/client_test.go
pkg/client/observatorium/config.go

With the removal of DEX authentication support (https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1676) the `AuthToken` parameter in the Observatorium configurations is not unused anymore.
This PR cleans up the parameter
* KFM runs correctly
* Tests pass

chore: remove Observatorium AuthToken config unused parameter

---

internal/kafka/internal/services/kafka.go
internal/kafka/internal/services/kafka_test.go

Revoke Kafka certificate even when the Kafka is not assigned to a data plane yet.
This could typically happen when a Kafka is created and deleted right away (before the accepted kafka reconciler runs) when KFM is running in `auto` mode. 
Code review and Unit test passing

fix(certs): revoke Kafka certificate even when the Kafka is not assigned to a data plane yet

---

internal/kafka/internal/migrations/20230329160000_add_distributed_lock.go
internal/kafka/internal/migrations/migrations.go
internal/kafka/internal/services/kafkatlscertmgmt/kafka_tls_certificate_management_service.go
internal/kafka/internal/services/kafkatlscertmgmt/secure_storage.go
internal/kafka/test/integration/distributed_lock_mgr_test.go
internal/kafka/test/integration/distributed_lock_test.go
pkg/shared/utils/sync/distributed_lock.go
pkg/shared/utils/sync/distributed_lock_mgr.go
pkg/shared/utils/sync/distributed_lock_mgr_test.go
pkg/shared/utils/sync/distributed_lock_mock.go
pkg/shared/utils/sync/distributed_lock_test.go

Currently, we already have a distributed lock mechanism based on the “SELECT ... FOR UPDATE” statement in the leader election code. 
However, this approach had one limitation: the lock table had to be prepopulated with the list of locks we wanted to support.
This new utility addresses this limitation by using a different approach. Instead of the “SELECT ... FOR UPDATE” statement, it uses the “INSERT INTO ... ON CONFLICT DO NOTHING” statement. This allows us to release the lock by simply sending a rollback to close the transaction and discard the row.
This new approach has several advantages:
1. There is no need to prepopulate the lock table.
2. The lock table does not grow indefinitely.
3. The lock ID can be generated dynamically at runtime.
While it is possible to achieve dynamic lock …

feat: add distributed lock utility

---

internal/kafka/internal/config/dynamic_scaling_config.go

`openshift-v4.11.36` is now the only enabled version on OCM for 4.11 on stage for creating new clusters. OCM will return a VersionsDisabled error when using any other 4.11 version.
```
{
"kind": "Error",
"id": "400",
"href": "/api/clusters_mgmt/v1/errors/400",
"code": "CLUSTERS-MGMT-400",
"reason": "Version 'openshift-v4.11.22' is disabled",
"details": [
{
"Error_Key": "VersionDisabled"
}
],
"operation_id": "57de23df-b0f2-4332-b06f-13006102be7c"
}
```
On Stage
```
$ ocm get /api/clusters_mgmt/v1/versions --parameter search="id like 'openshift-v4.11.%' and enabled='true'" | jq '.items[].id'
"openshift-v4.11.36"
```
Since this default value is used for our nightly tests, we need to bump it to the next enabled version of 4.11. 
Note that in Prod, previous 4.11 versions are still supported so …

feat: bump new_data_plane_openshift_version to openshift-v4.11.36

---

internal/kafka/internal/services/kafkatlscertmgmt/kafka_tls_certificate_management_service.go
internal/kafka/internal/services/kafkatlscertmgmt/kafka_tls_certificate_management_service_test.go
internal/kafka/internal/services/kafkatlscertmgmt/memory_storage.go
internal/kafka/internal/services/kafkatlscertmgmt/memory_storage_test.go

Attempts to `Lock` a key in the in-memory Let's Encrypt/certmagic storage result in a "file not found" error when `Store` for the same key has not yet been called. This change will create an entry for the key for either the `Lock` or `Store` operations and adds logging to allow users in development to obtain the generated LE account key.
1. Run KFM with these service template parameter
```
KAFKA_TLS_CERTIFICATE_MANAGEMENT_STRATEGY='true'
KAFKA_TLS_CERTIFICATE_MANAGEMENT_STORAGE_TYPE='in-memory'
KAFKA_TLS_CERTIFICATE_MANAGEMENT_EMAIL=your email
ENABLE_KAFKA_EXTERNAL_CERTIFICATE='true'
ENABLE_KAFKA_CNAME_REGISTRATION='true'
KAFKA_DOMAIN_NAME='kafka.bf2.dev'
```
and these secret template parameters
```
ROUTE53_ACCESS_KEY='..dev access key..'
ROUTE53_SECRET_ACCESS_KEY='..dev secret key..'
``` …

fix: create or update in-memory storage for both Lock and Store ops
