bf2fc6cc711aee1a0c2a/kas-fleet-manager

.github/workflows/ci.yaml, Makefile, README.md, internal/connector/internal/environments/integration.go, internal/kafka/internal/environments/integration.go, internal/kafka/test/integration/serviceaccounts_test.go, pr_check.sh, scripts/mas_sso_config.sh, scripts/mas_sso_setup.sh, scripts/mas_sso_teardown.sh, scripts/realmconfig/rhoas-realm-export.json, scripts/realmconfig/rhoas-sre-realm-export.json
Adding a script to create a local mas-sso using keycloak container with required realm config.
=> feat: adding script for creating local mas-sso instance

.github/labeler.yml
also add the documentation change labelling
=> ci: add openapi change PR labeler

.github/workflows/ci.yaml
Save some CI cycles by skipping draft PR.
A draft PR will be merged as soon as it is promoted as ready for review
=> ci: skip draft PR

.github/labeler.yml
This fix the following 'Error: YAMLException: unidentified alias ".md"' following https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/845
@akoserwal can I get your review again?
Code review is enough
- ~~[ ] CI and all relevant tests are passing~~
- ~~[ ] JIRA has created for changes required on the client side~~
=> chore(labeler): fix PR labeler

.github/CODEOWNERS
=> fix: add devexp-sdks for api changes

internal/connector/internal/handlers/connector_cluster.go, internal/connector/test/integration/feature_test.go, internal/kafka/internal/services/kas_fleetshard_operator_addon.go, internal/kafka/internal/services/kas_fleetshard_operator_addon_test.go, internal/kafka/test/integration/serviceaccounts_test.go, pkg/client/keycloak/config.go, pkg/services/keycloak.go, pkg/services/keycloak_test.go, pkg/services/keycloakservice_moq.go
Removed the attribute/protocol mapper logic
=> refactor: removed attribute/protocol mapper logic

Makefile, go.mod, go.sum, internal/kafka/internal/services/keycloak_kafka_test.go, pkg/client/keycloak/client.go, pkg/client/keycloak/client_moq.go, pkg/client/keycloak/client_test.go, pkg/client/keycloak/gocloak_moq.go, pkg/services/keycloak.go, pkg/services/keycloak_test.go
This fix the Authorization bypass in github.com/dgrijalva/jwt-go issue.
jwt-go allows attackers to bypass intended access restrictions in
situations with []string{} for m["aud"] (which is allowed by the
specification). Because the type assertion fails, "" is the value of
aud. This is a security problem if the JWT token is presented to a
service that lacks its own audience check. There is no patch available
and users of jwt-go are advised to migrat to golang-jwt at version 3.2.1
which we already have in our go.mod
1. Unit and integration test should pass
2. Code review from one of @akoserwal or @ziccardi as I'd like to get their expertly opinion on this upgrade of gocloak. …
=> chore(deps): update gocloak to v11 to fix CVE-2020-26160

internal/kafka/internal/services/kafka.go, internal/kafka/internal/services/kafka_test.go, internal/kafka/test/common/kafka_pollers.go, internal/kafka/test/common/util.go, internal/kafka/test/integration/kafkas_test.go, pkg/metrics/metrics.go
Update cluster status capacity used metric
Update to the integration tests should validate the change
- ~~[ ] JIRA has created for changes required on the client side~~
=> feat: update cluster_status_capacity_used metrics

internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/clusters_mgr_test.go
At the moment, when a cluster is in "waiting_for_kas_fleetshard_operator" state, it is not reconciled in the clusters worker. To fix this I added processWaitingForKasFleetshardOperatorClusters and reconcileWaitingForKasFleetshardOperatorCluster functions to Reconcile clusters waiting_for_kas_fleetshard_operator, in clusters_mgr.go.
1. Create a [Cluster](https://console.redhat.com/openshift)
2. run [ngrok](https://ngrok.com/)
3. Make sure your cluster is running `ocm list clusters --parameter search="name like '<ClusterName>'”`
4.`ocm get /api/clusters_mgmt/v1/clusters/<clusterID>| jq ' .name, .id, .multi_az, .[[cloud_provider.id](http://cloud_provider.id/)](http://cloud_provider.id/), .[[region.id](http://region.id/)](http://region.id/) '`
5. `./kas-fleet-manager serve`
6. Wait for the …
=> fix: Reconcile clusters in waiting_for_kas_fleetshard_operator to update addon parameters

internal/connector/internal/workers/connector_mgr.go, internal/connector/test/integration/features/connector-agent-api.feature
If a connector deployment is missing for  whatever reason during the lifecycle of a connector, that connector become stuck and can not be acted upon. If we detect such  scenario during reconciliation, we create the deployments again.
=> fix(connectors): MGDCTRS-494 fix Missing deployment inconsistency by recreating them during reconcile if they are missing.

pkg/environments/environment.go
Just tiny adjustments to comments to tidy them :)
=> style: removed some comment mispellings in environment.go

.github/workflows/ci.yaml, scripts/mas_sso_setup.sh
Update keycloak image to latest version 17.0.0-legacy => 17.0.1-legacy for integration testing
=> ci: Update keycloak image version for integration testing

internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/preparing_kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/ready_kafkas_mgr.go
Follow on from #870. Just a few comment adjustments to clarity the function of **KafkaManager structs within kafka_mgrs.
=> style: adjust kafka_mgr struct comments.

.github/CODEOWNERS, .github/labeler.yml
=> chore: pull request labelling for service template folder

templates/service-template.yml
1. Follow the steps in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/docs/deploying-kas-fleet-manager-to-openshift.md to deploy kas-fleet-manager to OpenShift. I used codeready containers for that.
2. Once the fleet manager has been deployed, try to interact with it and verify everything is working as expected
=> chore(envoy): update default image to v1.20.2

internal/kafka/internal/services/kafka.go, internal/kafka/test/integration/data_plane_endpoints_test.go
Follows up https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/789 after accidentally deleting the branch, which caused that PR to be closed. Once I force pushed, the Re-Open PR button was grayed out so opening a new PR.
=> fix(admin): only compare against actual versions when they are present and fallback to using desired versions if not

.gitignore, Makefile, pkg/workers/worker_interface.go, pkg/workers/worker_interface_moq.go
feat: added unit test coverage make targets
1. Run `make test/output/coverage/report` without `coverage.out` file present in the root dir and confirm that `coverage.out file not found` was displayed
2. Run `make test/html/coverage/report` without `coverage.out` file present in the root dir and confirm that `coverage.out file not found` was displayed
3. Run `make test` and confirm that `cover.out` is generated and processed at the end of the test execution (certain files are removed from the coverage report (e.g. mocked files...))
4. Run `make test/output/coverage/report` with `coverage.out` file present in the root dir and confirm that coverage results are displayed in the terminal
5. Run `make test/html/coverage/report` with `coverage.out` file present in the root dir and confirm that …
=> feat: added unit test coverage make targets

Makefile, docs/deploying-kas-fleet-manager-to-openshift.md, templates/service-template.yml
Follows up a discussion with @daveconde on setting up standalone clusters
=> feat(standalone): expose olm package as parameters

internal/connector/internal/workers/connector_mgr.go
Fixed connector update reconciliation to update last connector version that was updated. 
1. CI tests pass.
2. The reconcile worker should not be printing messages about updating the same connectors repeatedly.
=> fix(connectors): fixed missing connector worker lastVersion update

internal/kafka/internal/services/kafka.go, pkg/acl/access_control_list.go, pkg/auth/roles_authz_middleware.go, pkg/handlers/validation_builder.go, pkg/shared/utils/arrays/generic_array_utils.go, pkg/shared/utils/arrays/generic_array_utils_test.go, pkg/shared/utils/arrays/string_array_utils.go, pkg/shared/utils/arrays/string_array_utils_test.go
Added the following array utilities:
- **func FindFirst(predicate func(x interface{}) bool, values ...interface{}) (int, interface{})**: find the first occurrence matching the passed in predicate into the list of received values. Won't be needed anymore when we will have _generics_.
This function accepts a `...interface{}` instead of an `[]interface{}` because this way it can be used seamlessly with strings, int, int64, objects, etc. The drawbacks are:
- the values are converted to a []interface
- returned value is an interface{}
- **func FindFirstString(values []string, predicate func(x string) bool) (int, string)**: returns the index of the first string matching the passed in predicate and the string itself. `-1` and empty string if not found
- **func FilterStringSlice(values []string, …
=> feat: added array utilities

docker/Dockerfile_template, docker/Dockerfile_template_mocked
=> test(midstream): make sure the sso files are there

internal/kafka/internal/cmd/serviceaccounts/create.go, internal/kafka/internal/cmd/serviceaccounts/delete.go, internal/kafka/internal/cmd/serviceaccounts/list.go, internal/kafka/internal/cmd/serviceaccounts/resetcreds.go, pkg/client/redhatsso/client.go, pkg/client/redhatsso/integration/client_test.go, pkg/providers/core.go, pkg/services/sso/keycloak.go, pkg/services/sso/keycloak_service.go, pkg/services/sso/keycloak_service_builder.go, pkg/services/sso/keycloak_service_test.go, pkg/services/sso/redhatsso_service.go, pkg/services/sso/redhatsso_service_test.go
The builder now just takes the configuration and returns the appropriate KeycloakService instance (Keycloak or RedhatSSO)
=> refactor: refactored the keycloak service builder

CONTRIBUTING.md, DCO
* Add DCO (Developer Certificate of Origin)
* Update CONTRIBUTING.md to reference the legal related information
Related to https://issues.redhat.com/browse/MGDSTRM-7442
=> Add legal related content

internal/connector/internal/api/private/api/openapi.yaml, internal/connector/internal/api/private/model_connector_deployment_spec.go, internal/connector/internal/api/private/model_connector_deployment_status.go, internal/connector/internal/api/private/model_meta_v1_condition.go, internal/connector/internal/presenters/connector_cluster_status.go, internal/connector/test/integration/features/connector-agent-api.feature, openapi/connector_mgmt-private.yaml
fix https://issues.redhat.com/browse/MGDCTRS-718 by removing 3 deprecated fields.
1. `OCM_ENV=integration make test/integration/connector`
=> fix(connectors): MGDCTRS-718 Remove deprecated properties from agent APIs

internal/connector/internal/services/connector_namespaces.go, internal/connector/internal/services/connectors.go
Added optimistic locking using connector version in where condition to ensure the connector didn't change just before the update. 
CI tests should pass. 
=> fix(connectors): fixes MGDCTRS-753, use optimistic locking in connector updates

internal/connector/internal/handlers/authentication.go, internal/connector/internal/routes/route_loader.go, internal/connector/test/integration/cleanup/main.go, internal/kafka/internal/handlers/authentication.go, internal/kafka/internal/routes/route_loader.go, internal/kafka/test/integration/auth_test.go, internal/kafka/test/integration/data_plane_endpoints_test.go, internal/kafka/test/integration/federation_test.go, internal/kafka/test/mocks/kasfleetshardsync/kas-fleetshard-sync.go, pkg/client/keycloak/config.go
Updating all required occurrences of KafkaRealm with GetRealmProvider.
=> chore: replacing KafkaRealm with set provider

Makefile, internal/kafka/internal/metrics/component_versions_test.go
[MGDSTRM-7978](https://issues.redhat.com/browse/MGDSTRM-7978)
=> test: Increase unit test code coverage in internal/kafka/internal/metrics

pkg/acl/access_control_list.go, pkg/acl/access_control_list_middleware_test.go, pkg/acl/access_control_list_test.go
feat: increased unit test coverage in the pkg/acl package
Before changes the coverage was:
```
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/acl/access_control_list.go:12:					IsUserDenied						100.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/acl/access_control_list.go:24:					NewAccessControlListConfig				0.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/acl/access_control_list.go:31:					AddFlags						0.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/acl/access_control_list.go:36:					ReadFiles						0.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/acl/access_control_list.go:45:					readDenyListConfigFile					0.0%
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/acl/access_control_list_middleware.go:15: …
```
=> feat: increased unit test coverage in the pkg/acl package

templates/service-template.yml
This parameter was used as an alternate claim token id for the "org-id"
Follows up on https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/902
=> fix(service-template): properly interpret a parameter

internal/connector/internal/handlers/authentication.go, internal/kafka/test/integration/data_plane_endpoints_test.go, internal/kafka/test/integration/kafkas_test.go, internal/kafka/test/integration/require_terms_acceptance_middleware_test.go
This caused panic errors like the one observed in the
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/runs/6026913479?check_suite_focus=true
CI run
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x19e5c25]
goroutine 20984 [running]:
testing.tRunner.func1.2({0x1bda440, 0x32d6220})
/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1212 +0x218
panic({0x1bda440, 0x32d6220})
/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/panic.go:1038 +0x215
github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/internal/kafka/test/in …
```
=> fix(test): only attempt to delete a keycloak client when it is there to avoid panic errors

internal/kafka/test/integration/data_plane_endpoints_test.go, internal/kafka/test/integration/kafkas_test.go, internal/kafka/test/mocks/cloud_providers/cloud_providers.go
Fix larger kafka instances tests
- ~~[ ] JIRA has created for changes required on the client side~~
=> Fix larger kafka instances tests

Makefile, pkg/api/cluster_types_test.go, pkg/api/json_test.go, pkg/api/leader_lease_types_test.go, pkg/api/quota_service_types_test.go, pkg/api/semverutil_test.go
[MGDSTRM-7983](https://issues.redhat.com/browse/MGDSTRM-7983)
**Files changed:**
|   |  before % |   after % |   
|---|---|---|
|  cluster_types.go |  61.7 | 78.3  |   
|   json.go:| 0  | 100  |   
|  leader_lease_types.go | 0  |  100 |   
|  quota_service_types.go |  0 | 100  |   
| semverutil.go  |  90 |  96.8 |   
|   |   |
|---|---|
|  error.go |  adder to ignore coverage |   
|  metadata.go | added to ignore coverage  |
=> test: Increase unit test code coverage in pkg/api

internal/kafka/internal/config/kafka.go
re-add `--browser-url` command line flag which got removed during rebase.
=> fix: re-add browser url flag

internal/kafka/internal/kafkas/types/types.go, internal/kafka/internal/services/kafka.go
feat: dont add label to managed kafka CR if instance type is eval
=> feat: dont add label to managed kafka CR if instance type is eval

.github/CODEOWNERS
Addition of rarangan (raj) to code owners
Add RAj (rarangan) to code owners
=> Addition of raj to the code owners

internal/connector/internal/handlers/connector_validation.go, internal/kafka/internal/handlers/admin_kafka.go, internal/kafka/internal/services/util_test.go, internal/kafka/test/integration/data_plane_endpoints_test.go, pkg/services/sso/keycloak_service.go, pkg/services/types.go, pkg/shared/util.go, pkg/shared/utils/arrays/string_array_utils.go, pkg/shared/utils/arrays/string_array_utils_test.go
* Moved the `Contains` util into the string array utils package
* Added unit tests
* Refactored string utils test using Table Driven Tests
=> refactor: moved `Contains` util into the string arrays utils package

internal/connector/internal/api/private/api/openapi.yaml, internal/connector/internal/api/private/api_connector_clusters_agent.go, internal/connector/internal/handlers/connector_agent.go, internal/connector/internal/routes/route_loader.go, internal/connector/internal/services/connector_namespaces.go, internal/connector/test/integration/features/connector-agent-api.feature, openapi/connector_mgmt-private.yaml
Added agent endpoint to update namespace status
Included integration test must pass. 
=> feat(connectors): fixes MGDCTRS-824, added agent endpoint to update namespace status

internal/connector/test/integration/features/connector-agent-api.feature
Fixed a failing connector test. 
CI should pass. 
~~- [ ] All acceptance criteria specified in JIRA have been completed~~
=> fix(connectors): fixes failing connector test

config/kafka-instance-types-configuration.yaml, internal/kafka/test/integration/kafkas_test.go
Update the supported instance type configuration to have the correct limits. 
* Code Review
=> fix: update supported instance type limits

internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/clusters_mgr_test.go
Use the configured operators namespace for standalone clusters when creating pull secrets for operators
Also make sure that the namespace are created before referencing them in pull secrets
Fixes https://issues.redhat.com/browse/MGDSTRM-7991
/cc @daveconde this might interests you.
Try to use a standalone data plane clusters as indicated in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/docs/data-plane-osd-cluster-options.md#connecting-to-a-standalone-cluster and observe that no error message is printed out due to namespace not found
- ~~[ ] JIRA has created for changes required on …
=> fix(clusters): use the configured operators namespace for standalone clusters when creating pull secrets for operators

internal/connector/internal/handlers/connector_admin.go, internal/connector/internal/handlers/connectors.go, internal/connector/internal/services/connector_namespaces.go, internal/connector/internal/services/connectors.go, internal/connector/test/integration/features/connector-agent-api.feature
Fixes MGDCTRS-860, fixes admin API connector delete
Added integration test should pass. 
=> fix(connectors): fixes MGDCTRS-860, fixed admin API connector delete

internal/connector/internal/handlers/connector_cluster.go, internal/connector/test/integration/features/connector-cluster-api.feature
fix https://issues.redhat.com/browse/MGDCTRS-719
1. `OCM_ENV=integration make test/integration/connector`
=> fix(connectors): fix MGDCTRS-719 Non-org admin users can view addon parameters.

internal/kafka/constants/cluster.go, internal/kafka/internal/clusters/standalone_provider.go, internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/clusters_mgr_test.go
Follows up https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/pull/161#discussion_r859157081
Make sure that standalone clusters operators secret is properly referenced when set. This follows up  https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/pull/161#discussion_r859157081
/cc @MikeEdgar can you have a look?
Verification from @MikeEdgar 
- ~~[ ] JIRA has created for …
=> feat(clusters): configure operators pull secrets for standalone clusters

Makefile, pkg/auth/audit_log_middleware_test.go, pkg/auth/context_test.go, pkg/auth/operator_authz_middleware_test.go, pkg/auth/require_issuer_middleware_test.go, pkg/auth/require_org_id_middleware_test.go, pkg/auth/require_terms_acceptance_middleware_test.go
[MGDSTRM-7984](https://issues.redhat.com/browse/MGDSTRM-7984)
**Files changed:**
|   |  before % |   after % |   
|---|---|---|
|  audit_log_middleware.go |  73.9 | 73.9  |   
|  context.go:| 68.6  | 94.3  |   
| operator_authz_middleware.go|  72.2 | 83.3  |   
| require_issuer_middleware.go  |  88.9 |  88.9 | 
| require_org_id_middleware.go  |  85.7|  85.7 |   
| require_terms_acceptance_middleware.go  |  81.0 |  81.0 |   
| roles_authz_middleware.go  |  91.3 |  91.3 |   
|   |   |
|---|---|
|  helper.go |  added to ignore coverage |   
|  context_config.go | added to ignore coverage  |
=> test: Increase unit test code coverage in pkg/auth

internal/connector/internal/handlers/connector_agent.go, internal/connector/internal/services/connectors.go, internal/connector/test/integration/features/connector-agent-api.feature
Allow admin force delete to delete dangling connector deployments
Integration tests to verify fix included. 
=> fix(connectors): fixes MGDCTRS-881, allow admin force delete to delete dangling connector deployments

internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/clusters_mgr_test.go
Updates the type of the image pull secret to SecretTypeDockerConfigJson from SecretTypeDockercfg.
=> Update image pull secret type in dataplane cluster config

internal/kafka/internal/handlers/cloud_providers.go
Only 'Standard' Kafka instances should have the criteria of 'multi_az:true'. 'Developer' Kafka instances can be scheduled either in a single az or multi az cluster.
Gorm ignores a boolean criteria that is not set or has a false value. Because of this, MultiAZ does not need to be set in the criteria when checking capacity for 'Developer' Kafka instance type.
=> fix: allow multiAZ criteria to be configurable on cloud providers capacity reporting

internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/clusters_mgr_test.go
Update DockerConfigKey -> DockerConfigJsonKey for image-pull-secret used by data plane.
=> chore: Update image pull secret key

internal/connector/internal/handlers/connector_agent.go, internal/connector/internal/services/connector_cluster.go, internal/connector/internal/services/connector_namespaces.go, internal/connector/internal/workers/connector_mgr.go, internal/connector/internal/workers/namespace_mgr.go, internal/connector/test/integration/features/connector-agent-api.feature
fixes MGDCTRS-834, optimized and cleaned up namespace reconciliation to cleanly delete namespaces, 
fixes MGDCTRS-885, allow data plane to delete namespace with phase='deleted' status update
Integration tests to verify fixes must pass. 
=> fix(connectors): fixes MGDCTRS-834, optimized namespace reconciliation, fixes MGDCTRS-885, allow data plane to delete namespace with status update

internal/connector/internal/handlers/connector_cluster.go, internal/connector/internal/services/connector_cluster.go, internal/connector/test/integration/features/connector-agent-api.feature, openapi/connector_mgmt.yaml
Added query parameter reset_credentials to get addon params to reset client secret
Integration tests included must pass.
=> fix(connectors): fixes MGDCTRS-754, added query parameter reset_credentials to get addon params to reset client secret

pkg/flags/flags_test.go
test: pkg/flags tests
Coverage change: 0% -> 78.6%
- ~~[ ] JIRA has created for changes required on the client side~~
=> test: pkg/flags tests

Makefile
feat: removed environments config from test coverage
=> feat: removed environments config from test coverage

Makefile, docs/feature-flags.md, internal/kafka/internal/config/dataplane_cluster_config.go, internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/clusters_mgr_test.go, templates/service-template.yml
Closes https://issues.redhat.com/browse/MGDSTRM-8384. Follows up on
https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/pull/163#discussion_r862037539
- Added unit tests should pass
- Verification from @MikeEdgar in kas-installer that: (1) The identity provider is disabled when the flag `ENABLE_KAFKA_SRE_IDENTITY_PROVIDER_CONFIGURATION` is set to `false`. (2). When the parameter is removed or set to `true` identity provider configuration is enabled
This should not have any impact on our deployments environment as the `ENABLE_KAFKA_SRE_IDENTITY_PROVIDER_CONFIGURATION` is enabled by default.
- ~~[ ] JIRA has created for changes required on the …
=> feat(clusters): add a flag to enable disable configuration of identity provider

internal/connector/internal/config/connectors.go, internal/connector/internal/config/connectors_test.go, internal/connector/test/bad-connector-catalog/bad-connector-type.json
Added detailed error log messages, added unit test to verify messages
Included unit tests must pass. 
=> fix(connectors): fixes MGDCTRS-890, added detailed error log messages, added unit test to verify messages

internal/connector/internal/services/connectors.go, internal/connector/test/integration/features/connector-agent-api.feature
Fixed admin query to filter list of connectors by cluster_id
Integration test included
=> fix(connectors): fixes MGDCTRS-903: fixed admin query to filter list of connectors by cluster_id

internal/kafka/internal/workers/clusters_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_routes_cname_mgr.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_routes_cname_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/preparing_kafkas_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/provisioning_kafkas_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/ready_kafkas_mgr_test.go, internal/kafka/test/mocks/clusters/clusters.go, internal/kafka/test/mocks/data_plane/data_plane_cluster_config.go, pkg/quota_management/quota_management_list_config_test.go, pkg/quota_management/quota_management_list_test.go
kafkas and cluster managers unit tests
clusters_mgr_test.go 43.6%
ready_kafkas_mgr_test.go 26.3%
provisioning_kafkas_mgr_test.go 0%
preparing_kafkas_mgr_test.go 55%
kafkas_routes-cname_mgr_test.go 60%
kafkas_mgr_test.go 37.2%
deleting_kafkas_mgr_test.go 19.4%
accepted_kafkas_mgr_test.go 57.4%
clusters_mgr_test.go 95.8%
ready_kafkas_mgr_test.go 94.7%
provisioning_kafkas_mgr_test.go 84.6%
preparing_kafkas_mgr_test.go 92.5%
kafkas_routes-cname_mgr_test.go 93.3%
kafkas_mgr_test.go 91%
deleting_kafkas_mgr_test.go 91.7%
accepted_kafkas_mgr_test.go 87.2%
- ~~[ ] JIRA has created for changes required on the …
=> test: reconcilers tests

internal/kafka/internal/workers/clusters_mgr_test.go
fix: cluster worker tests
Confirm that CI passes
=> fix: cluster worker tests

Makefile, pkg/shared/config_test.go, pkg/shared/diff_test.go, pkg/shared/load_openapi_spec_test.go, pkg/shared/numutil_test.go, pkg/shared/util_test.go, pkg/shared/utils/arrays/generic_array_utils_test.go, pkg/shared/utils/arrays/string_array_utils_test.go, pkg/shared/utils/state_machine/grammar_test.go, pkg/shared/utils/stringscanner/simple_string_scanner_test.go, pkg/shared/utils/stringscanner/sql_string_scanner_test.go
Increase unit test code coverage in pkg/shared
[MGDSTRM-7989](https://issues.redhat.com/browse/MGDSTRM-7989)
filename| starting coverage % | finishing coverage %|
-- | -- | --
stringscanner/simple_string_scanner.go | 81 | 95.2
stringscanner/sql_string_scanner.go | 77.4 | 83.9
util/arrays/generic_array_util.go | 75 | 100
diff.go | 0 | 70
util.go | 0 | 100
load_openapi_spec.go | 0 | 100
util/statemachine/grammar.go | 0 | 100
util/statemachine/statemachine.go | 92.9 |  
numutil.go | 100 |  
util/arrays/string_array_util.go | 100 |  
get_project_root_dir.go | 93.3 |  
config.go | 82.9 |  
util/statemachine/builder.go | 77.8 |  
secrets/secrets.go 69.8 | 69.8 |  
filename| starting coverage % | finishing coverage %|
-- | -- | --
handle_error.go | 0 | add to ignore
write_json_response.go | 0 | …
=> test: Increase unit test code coverage in pkg/shared

Makefile, pkg/errors/errors.go, pkg/handlers/errors_test.go, pkg/handlers/framework_test.go, pkg/handlers/helpers_test.go, pkg/handlers/json_schema_validation.go, pkg/handlers/metrics_middleware_test.go, pkg/handlers/openapi_handler_test.go, pkg/handlers/presenter_test.go, pkg/handlers/prometheus_metrics_test.go, pkg/handlers/validation.go, pkg/handlers/validation_builder.go, pkg/handlers/validation_builder_test.go, pkg/handlers/validation_test.go
=> test: pkg/handlers unit tests

internal/connector/internal/services/connector_cluster.go, internal/connector/internal/services/connector_namespaces.go, internal/connector/internal/workers/cluster_mgr.go, internal/connector/internal/workers/connector_mgr.go, internal/connector/test/integration/features/connector-multitenancy-api.feature
Moved cascade deletes into reconciliation
Existing integration tests continue to work as expected. 
=> feat(connectors): fixes MGDCTRS-926: moved cascade deletes into reconciliation

internal/connector/internal/services/connector_types.go, internal/connector/test/integration/feature_test.go
Remove old associations when updating connector types
Existing CI tests for connector types should pass. 
=> fix(connectors): fixes MGDCTRS-938, remove old associations when updating connector types

internal/connector/internal/handlers/connector_admin.go, internal/connector/internal/routes/route_loader.go, internal/connector/test/integration/features/connector-admin-api.feature, openapi/connector_mgmt-private-admin.yaml
- MGDCTRS-927: add an endpoint to list connector type and related shard metadata
- MGDCTRS-933: add an admin endpoint to get cluster details
=> MGDCTRS-933: add an admin endpoint to get cluster details

Makefile, config/kafka-owner-list.yaml, internal/kafka/internal/config/kafka.go, internal/kafka/internal/config/kafka_test.go, internal/kafka/internal/services/kafka.go, templates/service-template.yml
Creating a draft pr to get input on the approach.
Only for development/testing allow to setup kafka owners using a configuration file.
=>  feat: adding option to configure kafka owners

Makefile, pkg/client/keycloak/client.go, pkg/client/keycloak/client_test.go
test: added unit tests for pkg/keycloak
=> test: added unit tests for pkg/keycloak

internal/connector/internal/api/admin/private/api/openapi.yaml, internal/connector/internal/api/admin/private/api_connector_clusters_admin.go, internal/connector/internal/api/admin/private/api_connector_types.go
=> fix(connectors): add missing generated files

internal/kafka/internal/handlers/kafka.go, internal/kafka/internal/handlers/validation.go, internal/kafka/internal/handlers/validation_test.go, internal/kafka/internal/services/kafka.go, internal/kafka/internal/services/kafka_test.go, internal/kafka/internal/services/kafkaservice_moq.go, internal/kafka/internal/services/quota.go, internal/kafka/internal/services/quota/ams_quota_service.go, internal/kafka/internal/services/quota/ams_quota_service_test.go, internal/kafka/internal/services/quota/quota_management_list_service.go, internal/kafka/internal/services/quota/quota_management_list_service_test.go, internal/kafka/internal/services/quotaservice_moq.go, internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr_test.go, pkg/auth/context.go, pkg/auth/context_config.go, pkg/auth/kfm_claims.go
Reimplementation of #988 without the use of a shared context.
We decided that we don't want to have a context, even if it didn't tie any of the validators to using it or expecting anything to be there. This has some drawback: some code needs to be executed more times to retrieve the same values: one time to validate it and one time to put it into the resulting object.
=> fix: removed validators side effects

internal/connector/internal/handlers/connector_namespace.go, internal/connector/internal/services/authz/authz_service.go, internal/connector/internal/services/connector_cluster.go, internal/connector/internal/services/connectors.go, internal/kafka/internal/services/kafka.go, pkg/acl/access_control_list_middleware.go, pkg/auth/audit_log_middleware.go, pkg/auth/context.go, pkg/auth/context_test.go, pkg/auth/kfm_claims.go, pkg/auth/require_org_id_middleware.go, pkg/auth/require_terms_acceptance_middleware.go, pkg/auth/roles_authz_middleware.go, pkg/services/sso/keycloak_service.go
This PR  removes the usage of the deprecated functions in favour of the KFMClaims object.
=> Remove deprecated

internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/clusters_mgr_test.go, pkg/services/sso/keycloak.go, pkg/services/sso/keycloak_service.go, pkg/services/sso/keycloak_service_proxy.go, pkg/services/sso/keycloak_service_test.go, pkg/services/sso/keycloakservice_moq.go, pkg/services/sso/osd_keycloak_service_moq.go, pkg/services/sso/redhatsso_service.go, pkg/services/sso/redhatsso_service_test.go
#963 created a new `OSDKeycloakService` interface. This PR concludes its work by moving the other related methods from KeycloakInterface to the OSDKeycloakService interface.
=> refactor: moved method from the generic KeycloakService interface to OSDKeycloakService

pkg/client/keycloak/config.go, pkg/client/redhatsso/client.go
Making API uri configuration for sso provider configurable
=> chore: updating api url for sso provider to be configurable

internal/kafka/internal/workers/clusters_mgr.go, internal/kafka/internal/workers/clusters_mgr_test.go
Jira: [MGDSTRM-8567](https://issues.redhat.com/browse/MGDSTRM-8567)
This change updates the version of the Observability Operator installed by KAS Fleet Manager from v3.0.9 to v3.0.10
1. Run KAS Fleet Manager locally.
2. The Observability Operator should be deployed in the `managed-application-services-observability` namespace.
3. Check `observability-operator-controller-manager` YAML for `spec/containers/image`. This value should be `quay.io/rhoas/observability-operator:v3.0.10`
=> chore: update Observability Operator to v3.0.10

internal/kafka/internal/migrations/20220524140500_add_kafka_marketplace_cloud_account_id.go, internal/kafka/internal/migrations/migrations.go
feat: added marketplace and cloud_account_id fields to kafka table
1. Run `make run` against `main` branch and confirm that the new fields added in this PR aren't present in the kafka_requests table
2. Run `make run` against this branch and confirm that the new fields added in this PR are present in the kafka_requests table and that the service runs without errors
=> feat: added marketplace and cloud_account_id fields to kafka table

.codecov.yml, .github/workflows/ci.yaml
Related to https://issues.redhat.com/browse/MGDSTRM-7486.
The aim is to integrate unit tests coverage with Github CI for this repository.
[Codecov](https://about.codecov.io/) is the tool/web service that we will make use of to accomplish this.
This PR adds the GitHub integration with Codecov.
* A [GitHub action](https://github.com/codecov/codecov-action) has been configured so the result of running the tests coverage is uploaded to Codecov
* Additionally, now a bot called [codecov-commenter](https://github.com/codecov-commenter) will report the coverage in a comment in PRs (that will be updated if the contents of the PR change)
* At the moment the coverage report is purely informational but it is possible to configure Codecov so a PR is blocked if the coverage fails to accomplish some …
=> Add initial codecov config

pkg/client/redhatsso/client_test.go, test/mocks/redhatsso.go
Increase unit test coverage in /pkg/client/redhatsso 
Jira : https://issues.redhat.com/browse/MGDSTRM-8140
Coverage Before: 0%
Coverage After: 90.6%
1. Run `make test`
2. Run `make test/html/coverage/report`
3. Should be able to see the increased test coverage
=> test: increase unit test coverage in /pkg/client/redhatsso

go.mod, go.sum, internal/kafka/internal/presenters/serviceaccounts.go, internal/kafka/test/mocks/service_accounts/service_accounts.go, pkg/api/service_account_types.go, pkg/services/sso/keycloak_service.go, pkg/services/sso/redhatsso_service.go, pkg/services/sso/redhatsso_service_test.go
This pr involves updating the service account SDK version from v0.3.0 to v0.4.0. It also involves handling the change of the `ownerId` field to `createdBy`
Jira: [Here](https://issues.redhat.com/browse/MGDSTRM-8587)
N/a
=> build: Update service Account SDK version

pkg/client/redhatsso/client_test.go
Add Created by to test to fix broken ci
=> fix: broken ci issue

internal/kafka/internal/api/dbapi/kafka_request_types.go, internal/kafka/internal/handlers/kafka.go, internal/kafka/internal/handlers/validation.go, internal/kafka/internal/presenters/kafka.go, internal/kafka/internal/services/kafka.go, internal/kafka/internal/services/kafkaservice_moq.go, internal/kafka/internal/services/quota.go, internal/kafka/internal/services/quota/ams_quota_service.go, internal/kafka/internal/services/quota/ams_quota_service_test.go, internal/kafka/internal/services/quota/quota_management_list_service.go, internal/kafka/internal/services/quotaservice_moq.go, pkg/client/ocm/client.go, pkg/errors/errors.go
https://issues.redhat.com/browse/MGDSTRM-8579
To test this we need an organization that has linked cloud accounts. Not quite sure how to obtain this.
=> Mgdstrm 8579

Makefile, pkg/services/sso/keycloak_service_builder_test.go, pkg/services/sso/keycloak_service_test.go, pkg/services/sso/redhatsso_service_test.go
Increase unit test coverage in /pkg/services/sso
| File  | Coverage Before | Coverage After |
|---|---|---|
| redhatsso_service.go  |  24.7% | 93.8% |
|  keycloak_service.go | 41%  | 87.1% |
|  keycloak_service_builder.go | 34.3%  | 83.3% |
1. Run `make test`
2. Run `make test/html/coverage/report`
3. Should be able to see the increased test coverage
=> test: increase unit test coverage in /pkg/services/sso

.github/dependabot.yaml
add dependabot for automatic package updates at a weekly interval
=> chore(dependabot): add dependabot for automatic package updates at a weekly interval

Makefile, pkg/services/sentry/config_test.go, pkg/services/sentry/sentry_test.go
Increase unit test code coverage in pkg/services/sentry
From the main branch run: `make test` followed by `make test/html/coverage/report`.
From this branch run the same commands and compare outputs for the  pkg/services/sentry folder.
|FileName|Starting %|Finishing %|
|----|----|----|
|sentry.go|0|95.2|
|providers.go|0|ignored|
|config.go|30|40 && Ignored|
=> test: Increase unit test code coverage in pkg/services/sentry

internal/connector/internal/migrations/202206060000_fix_connector_namespace_version_trigger.go, internal/connector/internal/migrations/migrations.go, internal/connector/internal/services/connector_namespaces.go, internal/connector/test/integration/features/connector-agent-api.feature
fixes MGDCTRS-1029, fixed namespace status update to avoid updating row when the status is the same
Added integration test should pass. 
=> fix(connectors): fixes MGDCTRS-1029, fixed namespace status update to avoid updating row when the status is the same

README.md
feat: test pr to trigger build in the app-interface CI
=> feat: test pr to trigger build in the app-interface CI

.github/workflows/ci.yaml, .golangci.yml, internal/kafka/test/common/kafka_pollers.go, internal/kafka/test/integration/admin_kafka_test.go, internal/kafka/test/integration/auth_test.go, internal/kafka/test/integration/cloudprovider_test.go, internal/kafka/test/integration/data_plane_cluster_test.go, internal/kafka/test/integration/data_plane_endpoints_test.go, internal/kafka/test/integration/federation_test.go, internal/kafka/test/integration/kafka_list_search_order_test.go, internal/kafka/test/integration/kafkas_test.go, internal/kafka/test/integration/observatorium_test.go, internal/kafka/test/integration/require_terms_acceptance_middleware_test.go, internal/kafka/test/integration/serviceaccounts_test.go, pkg/auth/audit_log_middleware_test.go, pkg/auth/operator_authz_middleware_test.go, pkg/auth/require_issuer_middleware_test.go, pkg/auth/require_org_id_middleware_test.go, pkg/auth/require_terms_acceptance_middleware_test.go, pkg/auth/roles_authz_middleware_test.go, pkg/client/observatorium/client_test.go, pkg/client/redhatsso/client.go, test/mocks/api_server.go
=> ci: added golangci action and enabled bodyclose linter

Makefile, internal/kafka/internal/handlers/admin_kafka.go, internal/kafka/internal/handlers/admin_kafka_test.go, internal/kafka/internal/handlers/cloud_providers.go, internal/kafka/internal/handlers/cloud_providers_test.go
test: kafka/handlers admin kafkas and cloud providers unit tests
=> test: kafka/handlers admin kafkas and cloud providers unit tests

pkg/services/sso/redhatsso_service.go, pkg/services/sso/redhatsso_service_test.go
fix(sso): fixes MGDSTRM-8776, fixes client secret reset check for existing account
Existing connector integration tests should continue to pass. Locally tested using redhat sso config as outlined in https://issues.redhat.com/browse/MGDSTRM-8191.
=> fix(sso): fixes MGDSTRM-8776, fixes client secret reset check for existing account

internal/kafka/internal/handlers/admin_kafka_test.go, internal/kafka/internal/handlers/cloud_providers_test.go
=> fix: fixed bodyclose linter error

internal/kafka/test/common/kafka_pollers.go, internal/kafka/test/common/util.go, internal/kafka/test/integration/kafkas_test.go
1. The way the test was setup e.g cluster ids, made the test pass most of the times since the cluster ids contained numbers which made the metric checker util to pass all the time : the checker uses `.Contains()`. 
2. Rewrites the metric checker a bit because the way the checker was written seemed suspicious. Notably https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/b08ee74bbe1c807f52646c59ed3015bd9e122f2e/internal/kafka/test/common/util.go#L245-L255 as it increased the count of found items while the item was not found: see https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/b08ee74bbe1c807f52646c59ed3015bd9e122f2e/internal/kafka/test/common/util.go#L247-L249 
The integration test should continue to pass
- ~~[ ] All acceptance criteria specified in JIRA have been …
=> test(integration): review instance type test to make it pass for the right reasons

config/dynamic-scaling-configuration.yaml, internal/kafka/internal/config/dataplane_cluster_config.go, internal/kafka/internal/config/dynamic_scaling_config.go, templates/service-template.yml
Related to https://issues.redhat.com/browse/MGDSTRM-8740.
Add ability to specify the maximum number of compute nodes to be used in each data plane cluster for each kafka instance type.
The mechanism to do this is by specifying that configuration in a configuration file, by default in `config/dynamic-scaling-configuration.yaml`.
When deployed through the service-template, a ConfigMap named `kas-fleet-manager-dynamic-scaling-config` containing the key `dynamic-scaling-configuration.yaml` is expected. This has been added to the service-template, and a template parameter called `DYNAMIC_SCALING_CONFIG` has been added, where the yaml contents are expected.
The format of the `config/dynamic-scaling-configuration.yaml` file is:
```
<instance-type-id-1>:
compute_nodes_config:
max_compute_nodes: …
```
=> feat: dynaming scaling: add configurability of max compute nodes per instance type

pkg/services/sso/keycloak_service.go, pkg/services/sso/keycloak_service_proxy.go, pkg/services/sso/redhatsso_service.go
This pr adds logging to redhatsso_service.go because Currently, no logging is implemented on the redhat sso service. This will help debug issues with sso integration
jira: https://issues.redhat.com/browse/MGDSTRM-8657
N/a
=> chore: add logging to redhatsso_service.go

internal/kafka/internal/kafkas/types/types_test.go
test: internal/kafka/internal/kafkas/types unit tests
=> test: internal/kafka/internal/kafkas/types unit tests

pkg/services/sso/redhatsso_service.go, pkg/services/sso/redhatsso_service_test.go, test/mocks/redhatsso.go
```
curl -v -X DELETE -H "Authorization: Bearer $(ocm token)" http://localhost:8000/api/kafkas_mgmt/v1/service_accounts/7d7426a8-9f03-408b-880f-997086b09cc3
```
```
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Vary: Authorization
< X-Operation-Id: caophai87d5n6qdrle2g
< Date: Tue, 21 Jun 2022 10:08:48 GMT
< Content-Length: 205
< 
{"id":"113","kind":"Error","href":"/api/kafkas_mgmt/v1/errors/113","code":"KAFKAS-MGMT-113","reason":"service account not found 7d7426a8-9f03-408b-880f-997086b09cc3","operation_id":"caophai87d5n6qdrle2g"}
```
```
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Vary: Authorization
< X-Operation-Id: caopi9a87d5n9gbkial0
< Date: Tue, 21 Jun 2022 10:10:45 GMT
< Content-Length: 205
< …
```
=> fix: changed redhatsso to return same errors as legacy sso

internal/kafka/internal/handlers/kafka_instance_types.go, internal/kafka/internal/handlers/kafka_instance_types_test.go
test: added unit tests for internal/handlers/kafka_instance_types
=> test: added unit tests for internal/handlers/kafka_instance_types

internal/connector/internal/services/connector_types.go, internal/connector/test/integration/connector-catalog-root/aws/aws-sqs-source-v1alpha1.json, internal/connector/test/integration/connector-catalog/aws-sqs-source-v1alpha1.json, internal/connector/test/integration/features/connector-admin-api.feature, internal/connector/test/integration/features/connector-agent-api.feature
=> fix: properly order shard_metadata entries to select the latest one

internal/connector/internal/config/connectors.go, pkg/shared/utils/files/files.go
Fixes https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-manager/issues/135
=> fix files.Walk utility function

internal/kafka/internal/handlers/cloud_providers_test.go, internal/kafka/internal/handlers/kafka_test.go
Increase unit test code coverage in internal/kafka/internal/handlers/kafka.go - (https://issues.redhat.com/browse/MGDSTRM-8765)
make test
make test/html/coverage/report
=> test: increased unit tests coverage for /handlers/kafka.go

Dockerfile
8.5 contains some security issues and it is strongly recommends updating
to the newest image version 8.6.
See https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.5-240&push_date=1646745223000
=> build(docker): update to ubi 8.6 as base image

build_deploy.sh
feat: added release creation at the end of the build_deploy.sh script
1. comment out everything up to the code changes in the `build-script.sh` file
2. [important] - comment out the third last line in the changed script (starting with `git push --force -o merge_request.create="true"`)
3. run the script without providing required env vars - nothing should happen
4. Get all required secrets from [vault](https://vault.devshift.net/ui/vault/secrets/managed-services-ci/show/rhosak-ci/bot) and run the script as follows (make sure to have the push step commented out):
```
AUTHOR_EMAIL=<secret_from_vault> AUTHOR_NAME=<secret_from_vault> GITLAB_TOKEN=<secret_from_vault>  ./build_deploy.sh
```
and confirm that the `managed-kafka-versions/services/kas-fleet-manager.yaml` config is updated with the …
=> feat: added release creation at the end of the build_deploy.sh script

go.mod, go.sum, pkg/server/api_server.go
Fix `Authorization bypass in github.com/dgrijalva/jwt-go` CVE warning reported in
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/security/dependabot/1
The package wasn't used so it is fine to remove it.
Integration test should continue to pass
=> build(deps): remove the github.com/dgrijalva/jwt-go package

internal/kafka/internal/clusters/cluster_builder.go, internal/kafka/internal/clusters/cluster_test.go, internal/kafka/internal/environments/integration.go, internal/kafka/test/integration/cluster_mgr_test.go
Review the test so that:
- The cluster is auto created by the reconciler
- Control the provider and region to avoid loads of cluster being created
- Align integration and dev env scaling config
- Only assert for standard capacity info and leave out developer because soon enough the cluster will be created in accordance to fleet isolation
- Cleanup clients created in sso
Run the tests with OCM_ENV set to development and observe that they pass
```
TEST_SUMMARY_FORMAT=standard-verbose TEST_TIMEOUT=2h make test/integration/kafka TESTFLAGS="-run TestClusterManager_SuccessfulReconcile"
```
NOTE: make sure that the sso is correctly set up.
=> test(cluster_mgr): fix the TestClusterManager_SuccessfulReconcile which was failing in dev env

pkg/services/types_test.go, pkg/services/util_test.go
Increase unit test coverage in pkg/services
jira: https://issues.redhat.com/browse/MGDSTRM-7988
1. Run `make test`
2. Run `make test/html/coverage/report`
4. Should be able to see the increased test coverage
=> test: increase coverage in pkg/services

pkg/errors/errors.go, pkg/errors/errors_test.go
Increase unit test code coverage in pkg/errors - https://issues.redhat.com/browse/MGDSTRM-8227
make test
make test/html/coverage/report
=> test: increased unit test coverage in /pkg/errors

pkg/services/sso/redhatsso_service.go
error should be returned first
=> fixing the err should be returned first

internal/kafka/internal/services/data_plane_kafka.go, internal/kafka/internal/services/data_plane_kafka_test.go, internal/kafka/test/integration/data_plane_endpoints_test.go
https://issues.redhat.com/browse/MGDSTRM-6982 - report a user friendly error message on data plane failed states
=> feat: report a user friendly error message on data plane failed states

pkg/db/config_test.go
test: pkg/db/config unit tests
=> test: pkg/db/config unit tests

build_deploy.sh
feat: temp change from yq to other libraries to compare and change tag and commitSha
=> feat: temp change from yq to other libraries to compare and change tag and commitSha

build_deploy.sh, create_release.sh, docker/Dockerfile_build
Containerize mkv mr creation for release
comment out commands in `build_deploy.sh` as in first commit and run:
```
AUTHOR_EMAIL=<from vault> AUTHOR_NAME=<from vault> GITLAB_TOKEN=<from vault> ./build_deploy.sh
```
confirm that MR is created in mkv repo (see example: https://gitlab.cee.redhat.com/mk-ci-cd/managed-kafka-versions/-/merge_requests/81)
- ~~[ ] CI and all relevant tests are passing~~
- ~~[ ] JIRA has been created for changes required on the …
=> Containerize mkv mr creation for release

internal/kafka/test/mocks/kasfleetshardsync/kas-fleetshard-sync.go
make the signature of the update functions in fleetshard-sync mock typed functions.
Tests should still pass.
=> refactor: make mock update functions in fleetshard-sync typed functions

internal/kafka/test/mocks/kasfleetshardsync/kas-fleetshard-sync.go
The nightly tests failed due to tests I added. In which the kas-fleetshard-sync mocks were unable to get ocm addons.
`Cluster '<clusterId>' not found`
This pr, removes calls the OCM for clusters with ProviderType standalone. Which will prevent the previous test and similar tests failing.
You can run the tests against development environment with the following:
- Run `ngrok http 8180`
- Set the kafka mas-sso-base-url to the ngrok url [Here](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/kafka/internal/environments/development.go#L21)
- Set the connectors mas-sso-base-url to the ngrok url also [Here](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/internal/environments/development.go#L19)
- Run the tests with …
=> feat: don't call OCM in development environment testing for clusters with standalone ProviderTypes

internal/kafka/test/integration/data_plane_cluster_test.go
The test was sometimes failing due to the reconciler not running before the assertion is made. Use
the poller to wait for the expected condition to happen within a reasonable timeout.
1. CI is passing
2. Running the test `make test/integration/kafka TESTFLAGS="-run TestDataPlaneCluster_GetManagedKafkaAgentCRAndObserveCapacityInfo"` several times passes as well
- ~~[ ] All PR comments are resolved either by addressing them or creating follow up tasks~~
- ~~[ ] Required metrics/dashboards/alerts have been added (or PR …
=> test(integration): harden the TestDataPlaneCluster_GetManagedKafkaAgentCRAndObserveCapacityInfo test

internal/kafka/test/integration/data_plane_cluster_test.go
This adjusts the poll interval and timeout to slighly bigger values to allow for the reconciler to
run. Previously in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1195, the poll
interval and reconciler interval was set to same values which seemed to causes intermittent issues.
Same as https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1195
=> test(integration): harden TestDataPlaneCluster_GetManagedKafkaAgentCRAndObserveCapacityInfo

Makefile
Refactor the Makefile to use makefile variables to reference some of the binaries we are using.
The criteria that has been used to move some of the binaries references to variables is to move those where the binary might not be "by default" installed in the system or it is potentially susceptible to be changed by the user.
Makefile targets still work as expected.
=> refactor: makefile: reference binaries using variables

internal/kafka/internal/config/kafka_supported_instance_types_test.go, internal/kafka/internal/workers/cluster_mgrs/dynamic_scaleup_mgr.go, internal/kafka/internal/workers/cluster_mgrs/dynamic_scaleup_mgr_test.go, pkg/errors/errors.go, pkg/errors/errors_test.go
Based on work done in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1205, this PR refactors the introduced logic.
=> refactor: dynamic data plane scale up reconciler logic

internal/kafka/internal/workers/cluster_mgrs/dynamic_scaleup_mgr.go
To help getting insights and debugging.
Examples of shown logs exercising different parts of the code (without any order in particular):
```
I0728 11:04:02.120685   28227 dynamic_scaleup_mgr.go:440] capacity consumption value of biggest kafka size of locator '{provider:p1 region:r1 instanceTypeName:t1}': '2'
I0728 11:04:02.120778   28227 dynamic_scaleup_mgr.go:403] summary consumption evaluation of cluster consumption '{Region:r1 InstanceType:t1 ID: ClusterId: Count:1 CloudProvider:p1 MaxUnits:2 Status:ready}' for locator '{provider:p1 region:r1 instanceTypeName:t1}'
I0728 11:04:02.120793   28227 dynamic_scaleup_mgr.go:403] summary consumption evaluation of cluster consumption '{Region:r1 InstanceType:t1 ID: ClusterId: Count:4 CloudProvider:p1 MaxUnits:6 Status:ready}' for locator …
```
=> feat: add logging to dynamic scale up functionality

internal/kafka/internal/services/kafka.go, internal/kafka/internal/services/kafka_test.go
Related to https://issues.redhat.com/browse/MGDSTRM-9309
The `GetAvailableSizesInRegion` method, used in the list cloud provider regions endpoint (/{id}/regions) has been updated so only region limit checks are performed when dynamic scaling is enabled. The behavior when manual scaling is disabled has been kept the same.
The reason of this change is due to in dynamic scaling mode as long as the region limit is not hit there should evantually be capacity available. So we consider that size should be available as long as the region limit is not hit, even if at that moment the kafka size cannot fit in any already existing cluster.
unit and integration tests should still pass.
Calling the cloud provider endpoint enabling and disabling dynamic scaling should behave differently when there is no …
=> feat: GetAvailableSizesInRegion only checks region limts when dynamic scaling enabled

pkg/workers/leader_election_mgr_test.go, pkg/workers/reconciler_config_test.go, pkg/workers/worker_interface_test.go
Increase coverage for pkg/workers
jira: https://issues.redhat.com/browse/MGDSTRM-7990
1. Run `make test`
2. Run `make test/html/coverage/report `
3. Should be able to see the increased code coverage
=> test: increase coverage for pkg/workers

docs/architecture/data-plane-osd-cluster-dynamic-scaling.md
=> docs(dynamic_scaling): add dynamic scaling documentation

.spectral.yaml, Makefile, README.md
updates spectral and the rhoas guidelines to latest release
Bumps Spectral Linter and RHOAS Guidelines versions.
1. Check out the branch
2. Run `make openapi/spec/validate`
The make file target should look for the older version, if it exists it will remove it then install and link the new executable.
=> refactor: updates spectral and the rhoas guidelines to latest release

docs/data-plane-osd-cluster-options.md
Follows up https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1241#discussion_r946642781
=> docs(dataplane): add a note on the impact of turning on dynamic scaling

README.md
Updat README with some minor formatting changes. Those include fixing formatting issues, making the formatting consistent throughout the file, ...
=> chore: README minor formatting changes

internal/connector/internal/services/connector_cluster.go, internal/connector/internal/services/connectors.go, internal/connector/test/integration/cucumber_steps.go, internal/kafka/internal/config/gcp_test.go, internal/kafka/test/common/util.go, pkg/client/redhatsso/client.go, pkg/db/context.go, pkg/server/logging/logging.go, pkg/server/logging/writer.go, pkg/services/signalbus/pg_signalbus.go, pkg/services/sso/keycloak_service.go, pkg/shared/config.go, pkg/shared/config_test.go, pkg/shared/util.go, test/cucumber/http_request.go, test/cucumber/sql.go, test/mocks/redhatsso.go
Wile getting up to speed with the code, I've fixed some minor issue here and there:
- fix warning about methods on both value and pointer receivers
- make slices with know len
- add CloseQuietly utility function
- fix warning about methods on both value and pointer receivers
- remove package name from const
- improve CreateTempFileFromStringData
- error string should not be capitalised
=> Minor cleanuop

internal/connector/internal/config/connectors_quota_config.go, internal/connector/internal/config/connectors_quota_config_test.go
=> MGDCTRS-1232: validate connectors-quota-configuration

internal/connector/internal/presenters/connector.go, internal/connector/test/integration/features/connector-agent-api.feature
=> fix(MGDCTRS-844): remove error message when connector not failed or stopped

internal/kafka/test/common/util.go, pkg/client/redhatsso/client.go, test/cucumber/http_request.go
For some reason, the linter is unable to properly process the CloseQuietly method, see: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/actions/runs/2883674352
=> fix linter findings

internal/kafka/internal/services/quota/ams_quota_service.go
This PR performs some refactorings aimed to simplify the logic and improve readability of the AMS Quota service type methods.
Look at the different commits and their message details for more information about the performed changes and the motivations.
Tests pass.
=> refactor: AMS Quota service refactorings

docs/architecture/cluster-management-interface-and-implementations.md, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go, internal/kafka/providers.go, internal/kafka/test/helper.go
Move the reconciler onto the package that hosts all cluster specific reconcilers.
All unit and integration test are passing
=> refactor(cluster_mgrs): move the cluster manager onto the cluster_mgrs package

pkg/services/queryparser/query_parser.go
A small change to improve error message in case of query parser error.
=> refactor: minor change in query parser error message.

pkg/db/context_test.go
(https://issues.redhat.com/browse/MGDSTRM-9003) - Increase unit test code coverage in pkg/db/context.go
make test
make test/html/coverage/report
=> test: increase coverage in pkg/db/context.go

Makefile
Update gotestsum to v1.8.2.
Integration tests pass
=> chore: update gotestsum to v1.8.2

pkg/client/ocm/client.go, pkg/client/ocm/client_test.go
The ams organisation id and external id mapping should never change. This method gets called multiple times when validating a Kafka request on POST /kafkas. We should cache the results from ams to avoid calling it multiple times. 
Related JIRA: https://issues.redhat.com/browse/MGDSTRM-8913
Investigation on reducing calls of `GetOrganisationIdFromExternalId()` was also part of this issue. No changes are made to reduce the current calls due to the following reasons:
1. It was decided previously that validators should only perform validation. It should avoid having data passed between them even if calls to retrieve certain information may be duplicated. (See discussion in [PR#988](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/988#issuecomment-1115879161))
2. Both …
=> feat: cache ams external id to org id mapping

internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_down_mgr.go
=> refactor(dynamic_scale_down_mgr): quote the cluster_id to deal with the case of an empty string

.github/workflows/ci.yaml, Dockerfile, docker/Dockerfile_template, docker/Dockerfile_template_mocked
=> feat: update Go version to 1.19.1

internal/connector/internal/handlers/connector_admin.go, internal/connector/internal/handlers/connector_validation.go, internal/connector/internal/handlers/connectors.go, internal/connector/internal/services/connectors.go
A clean up of unused and undefined url parameter named `tid`. 
1. `OCM_ENV=integration make test/integration/connector`
=> fix(connectors): MGDCTRS-1416: removed tid Undeclared query param referenced in ConnectorsHandler.Create

Dockerfile, docker/Dockerfile_build
feat: updated base ubi images to the latest major version
Verified already locally that the image builds and runs, but to double check, run:
```
docker build -t kfm -f Dockerfile .
docker run -i kfm 
```
Don't try to run the `_build` image as this can potentially create unnecessary MR (you can still build it if you like)
- ~~[ ] CI and all relevant tests are passing~~
=> feat: updated base ubi images to the latest major version

Makefile, docs/deploying-kas-fleet-manager-to-openshift.md, docs/feature-flags.md, internal/kafka/internal/config/dataplane_cluster_config.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go, pkg/constants/operators.go, templates/service-template.yml
Jira: [MGDSTRM-9499](https://issues.redhat.com/browse/MGDSTRM-9499), [MGDSTRM-8588](https://issues.redhat.com/browse/MGDSTRM-8588)
This PR will allow for the Observability Operator version to be provided via a flag.
Also the default version of the Observability Operator deployed by KFM is upgraded from v3.0.10 to v3.0.14
* From this PR, KFM can be run locally with the flags:
* `--observability-operator-index-image=quay.io/rhoas/observability-operator-index:v3.0.10`
* `--observability-operator-starting-csv=observability-operator.v3.0.10`
This will install v3.0.10 of the Observability Operator. Allow the Operator to fully install then stop KFM running locally.
* Run KFM again with flags for upgrade index image and starting CSV values:
* …
=> feat: make Observability Operator version used by KFM configurable by CLI flags

pkg/client/ocm/client.go
Returning `false` in a `.Each` loop stops the iteration. This could lead to us only returning the first item from the original quota list while we are interested in applying the filter throughout all the items of the original quota list.
Instead of a return, we've to break the inner loop to only stop iterating the inner loops.
``
=> fix(ocm): iterates through all the list of quota and apply filter once

internal/kafka/internal/services/quota/ams_quota_service.go, internal/kafka/internal/services/quota/ams_quota_service_test.go
Related to https://issues.redhat.com/browse/MGDSTRM-9370.
For Kafkas created in `gcp` Cloud Provider currently the only supported billing models are prepaid (standard) and consumption based pricing on redhat marketplace. This PR updates AMS quota logic to limit the billing models for Kafkas created in `gcp` to the supported billing models.
* Create a Kafka instance with `gcp` cloud provider with AWS marketplace billing model. An error should be returned.
* Create a Kafka instance with `gcp` cloud provider with RHM marketplace billing model. It should succeed (as long as there is enough quota)
* Create a Kafka instance with `gcp` cloud provider on prepaid billing model. it should succed (as long as there is enough quota)
* The behavior of creating Kafka instances with `aws` cloud provider …
=> feat: Ensure rhosak gcp onlybilled in rhm

internal/kafka/internal/config/dynamic_scaling_config.go, internal/kafka/internal/config/dynamic_scaling_config_test.go
1. The first commit adds in a small code refactoring in the concerned configuration file
2. The second commit adds the missing unit test cases to partially address https://issues.redhat.com/browse/MGDSTRM-8921
The added unit tests should pass
=> Add dynamic scaling config unit tests

pkg/client/observatorium/api.go
The metrics queries can be processed in parallel to further improve the metrics latency time. At the moment the processing is done sequentially meaning which means that the latency will be the total time it takes for all sequential calls to observatorium to finish. Doing it in parallel means that the time it now takes will be the largest time it takes for one operation to complete
=> perf(metrics): distribute metrics queries

internal/kafka/internal/services/data_plane_kafka.go, internal/kafka/internal/services/data_plane_kafka_service_moq.go, internal/kafka/internal/services/data_plane_kafka_test.go, internal/kafka/test/integration/data_plane_endpoints_test.go, pkg/metrics/metrics.go
Adds reserved instances metrics. The details of the implementation are available in the below linked JIRA.
Closes https://issues.redhat.com/browse/MGDSTRM-9679
The added unit & integration tests should pass.
=> feat(prewarming): add reserved instances metrics

internal/kafka/test/integration/cluster_metrics_test.go, internal/kafka/test/integration/cluster_service_test.go
See the commits for description
The test should continue to pass
=> fix missing columns errors and unmarshaling errors from some integration tests

internal/connector/test/integration/features/connector-cluster-admin-api.feature
=> fix(cos): use the right admin role name

.github/workflows/ci.yaml, Dockerfile, docker/Dockerfile_template, docker/Dockerfile_template_mocked
=> feat: update Go version to 1.19.2

internal/kafka/constants/kafka.go
=> refactor(kafka): remove unused constant

internal/kafka/internal/config/dataplane_cluster_config.go, internal/kafka/internal/handlers/data_plane_kafka.go, internal/kafka/internal/services/clusters.go, pkg/api/cluster_types.go, pkg/api/metadata.go, pkg/auth/require_issuer_middleware.go, pkg/auth/roles_authz_middleware.go, pkg/client/keycloak/client.go, pkg/client/observatorium/api.go, pkg/services/queryparser/query_parser.go, pkg/shared/utils/arrays/common_predicates.go, pkg/shared/utils/arrays/common_predicates_test.go, pkg/shared/utils/arrays/generic_array_utils.go
This PR contains:
*  a few examples of using the new array utilities.
* examples of adding new common predicates for common usage patterns.
=> chore: example of using the new array utilities

Makefile
integration test folders have to be ignored from the coverage report. They are currently not ignored and it leads to comments like https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1353#issuecomment-1285373016
=> chore: ignore test folders from coverage report

internal/kafka/internal/handlers/admin_kafka.go, internal/kafka/internal/handlers/validation.go, pkg/shared/util.go, pkg/shared/util_test.go, pkg/shared/utils/arrays/common_predicates.go, pkg/shared/utils/arrays/common_predicates_test.go
The `IsNilPredicate` function threw a `panic` error when `T` was not billable.
The current PR address that issue and exposes the common predicates as a utility in the `shared` package.
Finally, the `StringEqualsIgnoreCase` util is added, accepting both `string` or `string*` and the `StringEqualIgnoreCasePredicate` now accepts T as `string | *string` instead of `any`
This PR contains the following:
* a fix for `IsNilPredicate` that threw a panic error when the received `T` was not nillable
* A new `StringEqualIgnoreCasePredicate` accepting both `string` and `*string`
* A new `StringEmpty` utility accepting both `string` and `*string` with an optional `trim` parameter
* Array predicates have been changed to rely on the `shared` utility functions (when needed)
=> fix: fixed an issue in the IsNil predicate function

.github/workflows/ci.yaml, Dockerfile, docker/Dockerfile_template, docker/Dockerfile_template_mocked
=> feat: update Go version to 1.19.3

scripts/mas_sso_config.sh
The bash timeout command is not available on all systems. Replaced the `timeout` with a `while` loop.
The Keycloak config script was checking if keycloak was available using the `timeout command` to interrupt an infinite loop used to check the keycloak status.
However, the timeout command is not available by default on many systems (mac, for example), and the keycloak setup failed.
Moreover, if keycloak was not ready, the script didn't stop and all subsequent `curl` commands were failing.
With this PR we won't have that dependency anymore and, if keycloak is not ready, the script doesn't attempt the cur commands.
=> fix: removed dependency on the bash timeout command

Makefile, build_deploy.sh
feat: force pulling latest image(s) when building docker images
=> feat: force pulling latest image(s) when building docker images

docs/automated-testing.md, internal/kafka/test/helper.go, internal/kafka/test/integration/admin_kafka_suspension_test.go, internal/kafka/test/integration/cluster_mgr_test.go, internal/kafka/test/integration/data_plane_endpoints_test.go
Ensure services accounts are deleted 
Run the integration tests locally against a fresh installed keycloak container.
After the test finishes, go to http://localhost:8180/auth/admin/master/console/#/realms/rhoas/clients and observe that there is no service that starts with `canary-` nor `kas-fleet-shard-agent`. 
When asked for the username & password, use `admin` in both cases.
=> test(integration): ensure service accounts are deleted

internal/kafka/internal/services/data_plane_kafka.go, internal/kafka/internal/services/kafka.go, internal/kafka/internal/services/kafka_test.go, internal/kafka/internal/services/kafkaservice_moq.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/preparing_kafkas_mgr.go, internal/kafka/test/integration/admin_kafka_suspension_test.go, internal/kafka/test/integration/kafka_create_test.go, pkg/metrics/metrics.go
=> feat: expose metric with kafka status set timestamp

internal/kafka/internal/services/kafka_test.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go, pkg/metrics/metrics.go
fix: minor issues with newly added metric
=> fix: minor issues with newly added metric

internal/kafka/internal/migrations/20221104090000_remove_the_wrongly_auto_created_cluster_from_stage_environment_with_id_cdhunvd8igjhbi0nmtt0.go, internal/kafka/internal/migrations/migrations.go
=> fix(db): remove the newly registered clusters creation request

internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go, internal/kafka/test/integration/admin_kafka_suspension_test.go
=> chore: added Suspended, Suspending and Resuming statuses to the request status count metric

internal/kafka/internal/services/quota/default_quota_service_factory.go, internal/kafka/internal/services/quota/quota_management_list_service_test.go, internal/kafka/internal/services/quota_service_factory.go, internal/kafka/internal/services/quota_service_factory_moq.go, internal/kafka/internal/workers/kafka_mgrs/deleting_kafkas_mgr_test.go
Some of our code contained misspell of the quota word. This PR fixes the misspell by changing from `quoata...` to `quota...`.
=> fix: fix quota misspells

config/dynamic-scaling-configuration.yaml
Use a memory-optimized instance for them
=> chore: change default gcp kafka standard instance to custom-4-32768-ext

internal/kafka/internal/config/kafka_supported_instance_types.go, internal/kafka/internal/services/data_plane_kafka.go
To fix failing CI:https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/actions/runs/3470441039/jobs/5798647744
`make lint` should run successfully
=> fix(linting): address a few linting issues

openapi/connector_mgmt-private-admin.yaml
=> fix(connectors):fix reference to List scheme in OpenAPI admin definition

internal/connector/internal/services/connector_types.go, internal/connector/test/integration/connector-metadata/aws-sqs-source-v1alpha1-metadata.yaml, internal/connector/test/integration/connector-metadata/log_sink_0.1_metadata.yaml, internal/connector/test/integration/features/connector-api.feature, internal/connector/test/missing-connector-metadata/log_sink_0.1_metadata.yaml, internal/connector/test/unknown-connector-metadata/aws-sqs-source-v1alpha1-metadata.yaml, internal/connector/test/unknown-connector-metadata/log_sink_0.1_metadata.yaml
Fixed query to correctly count number of featured connectors
CI tests should pass.
=> fix(connectors): fixes MGDCTRS-1691, fixed query to correctly count number of featured connectors

internal/kafka/internal/services/data_plane_kafka.go, internal/kafka/internal/services/data_plane_kafka_test.go
Improves it by improving visibility of empty/nil values and clarify some concepts.
Logging and returned service errors have been updated in data plane kafka service code.
Tests pass
=> feat: improve logging and returned errors content in data plane kafka

internal/kafka/internal/services/data_plane_kafka.go, internal/kafka/internal/services/data_plane_kafka_test.go, internal/kafka/internal/services/kafka.go, internal/kafka/internal/services/kafka_test.go, internal/kafka/internal/services/kafkaservice_moq.go, internal/kafka/internal/workers/kafka_mgrs/accepted_kafkas_mgr_test.go
Acronyms/Initialisms should have a consistent case: https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Tests pass
=> refactor: rename kafka service GetById to GetByID

internal/connector/internal/services/connector_cluster.go, internal/kafka/internal/services/clusters.go, internal/kafka/internal/services/clusters_test.go, internal/kafka/internal/services/clusterservice_moq.go, internal/kafka/test/mocks/kasfleetshardsync/kas-fleetshard-sync.go, pkg/auth/auth_agent_service.go, pkg/auth/auth_agent_service_moq.go, pkg/auth/operator_authz_middleware.go, pkg/auth/operator_authz_middleware_test.go
Acronyms/Initialisms should have a consistent case: https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Tests pass
1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item 
4. Check if in the left menu the feature X is not so long present.
If manual verifications required, please provide an environment where the reviewers can easily validate the changes if possible to speed up the review process. 
-->
=> refactor: rename cluster service GetClientId to GetClientID

internal/kafka/internal/services/clusters.go, internal/kafka/internal/services/clusters_test.go, internal/kafka/internal/services/clusterservice_moq.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go
Acronyms/Initialisms should have a consistent case
Tests pass
=> feat: rename cluster service ListAllClusterIds initialism

internal/kafka/internal/services/clusters.go, internal/kafka/internal/services/clusterservice_moq.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go
Acronyms/Initialisms should have a consistent case
Tests pass
=> refactor: rename clusterIds initialisms in cluster service methods

internal/connector/internal/handlers/connector_admin.go, internal/connector/internal/handlers/connector_types.go, internal/connector/internal/handlers/connectors.go
Fixes MGDCTRS-1547, fixed connector type id length check, bumped id length to 63
CI tests should pass.
=> fix(connectors): fixes MGDCTRS-1547, fixed connector type id length check, bumped id length to 63

README.md, internal/connector/internal/services/vault/config.go, secrets/vault/.gitignore
Changed the default location of connector vault credentials config files to secrets/vault.
CI should pass with existing unit tests.
=> feat(connectors): moved vault credentials config files

.github/workflows/openapi_update.yaml
This pr enables changes to the openapi spec to be push to the core SDK repo aswell as the other SDKs.
https://issues.redhat.com/browse/MGDX-284
=> chore: now will push openapi changes to core sdk

internal/connector/internal/services/connector_types.go, internal/connector/test/integration/connector-metadata/aws-sqs-source-v1alpha1-metadata.yaml, internal/connector/test/integration/features/connector-api.feature
Removed computed category-features, refactored labels query to always return all labels with counts for connector types that meet the search criteria
Updated CI tests should pass.
=> feat(connectors): fixes MGDCTRS-1753, removed computed category-features, refactored labels query

internal/connector/internal/migrations/202212050000_add_orgid_annotations.go, internal/connector/internal/migrations/migrations.go, internal/connector/internal/services/connector_types.go
Added migration to add annotations for existing clusters and connectors
CI including migration tests should pass.
=> fix(connectors): fixes MGDCTRS-1755, added migration to add annotations for existing clusters and connectors

internal/connector/internal/handlers/connectors.go, internal/connector/test/integration/features/connector-api.feature
A json-patch can be applied to original resource json, and diffed to convert it into a merge-patch. 
CI tests added for json-patch should pass.
=> fix(connectors): fixes MGDCTRS-975, json-patch is now supported for connector patch request

config/quota-management-list-configuration.yaml, go.mod, pkg/quota_management/account.go, pkg/quota_management/account_test.go, pkg/quota_management/billing_model.go, pkg/quota_management/expiration_date.go, pkg/quota_management/expiration_date_test.go, pkg/quota_management/organisation.go, pkg/quota_management/quota.go, pkg/quota_management/quota_management_list_config_test.go
Added management of quota expiration in quota list. This way it reflects what happens on AMS too (when the trial expires, AMS returns 0 allowed instances)
=> feat: added quota expiration in quota list

internal/kafka/internal/acl/enterprise_cluster_registration_access_list_middleware.go, internal/kafka/internal/acl/enterprise_cluster_registration_access_list_middleware_test.go, internal/kafka/internal/acl/enterpsise_cluster_registration_access_list_test.go
test: enterprise cluster endpoint middleware unit tests
=> test: enterprise cluster endpoint middleware unit tests

internal/kafka/internal/api/public/api/openapi.yaml, internal/kafka/internal/api/public/api_default.go, openapi/kas-fleet-manager.yaml
=> fix(openapi): change response type of cluster-registration endpoint

internal/kafka/test/integration/cluster_mgr_test.go
=> test(cluster_mgr_test): update error message

internal/kafka/internal/api/public/api/openapi.yaml, internal/kafka/internal/api/public/model_kafka_request.go, openapi/kas-fleet-manager.yaml
Signed-off-by: hemahg <hhg@redhat.com>
There are 3 new statuses `suspending`, `suspended`, and `resuming` supported by the backend but not included in the open API. The PR includes the new statues
=> Included new statuses

Makefile, README.md
Add documentation on how to configure KFM to be able to deploy data plane clusters located in GCP.
=> doc: add GCP configuration documentation in README.md

internal/kafka/internal/handlers/validation.go
print numbers correctly in validation message
=> fix(clusters): print numbers correctly in validation message

Makefile
To get latest changes and fixes. A notable addition is the support for generic interface generation
Run `make generate` and verify no errors nor new changes related to moqs are generated.
=> chore: update moq to v0.3.0

.github/workflows/ci.yaml, Dockerfile, docker/Dockerfile_template, docker/Dockerfile_template_mocked
=> feat: update Go version to 1.19.4

internal/kafka/internal/services/kafka.go
Some methods of the AWS Route53 client were using string to designate an AWS action. Make use of the typed KafkaRoutesAction string instead.
Tests pass
=> refactor: use typed KafkaRoutesAction instead of generic string

config/kafka-instance-types-configuration.yaml
Clarify lifespanSeconds attribute documentation in kafka instances configuration.
To align with the current behavior after recent long lived evaluation instances
=> doc: clarify lifespanSeconds config behavior

config/dataplane-cluster-configuration.yaml, config/provider-configuration.yaml, internal/kafka/internal/handlers/validation_test.go, internal/kafka/internal/services/cluster_placement_strategy.go, internal/kafka/internal/services/cluster_placement_strategy_test.go, internal/kafka/internal/services/clusters.go, internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_down_mgr.go, internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_down_mgr_test.go, internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_up_mgr.go, internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_up_mgr_test.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go, internal/kafka/test/integration/cluster_list_enterprise_test.go, internal/kafka/test/integration/cluster_metrics_test.go, internal/kafka/test/integration/cluster_mgr_test.go, pkg/api/cluster_types_test.go
feat: set used/max metrics for enterprise dataplane clusters
=> feat: set used/max metrics for enterprise dataplane clusters

internal/kafka/internal/api/public/api/openapi.yaml, internal/kafka/internal/api/public/api_enterprise_dataplane_clusters.go, internal/kafka/internal/api/public/model_enterprise_cluster_with_addon_parameters.go, internal/kafka/internal/handlers/cluster.go, internal/kafka/internal/handlers/cluster_test.go, internal/kafka/internal/presenters/cluster.go, internal/kafka/internal/presenters/cluster_test.go, internal/kafka/internal/routes/route_loader.go, internal/kafka/test/integration/cluster_get_enterprise_test.go, openapi/kas-fleet-manager.yaml
feat: add get enterprise cluster endpoint
=> feat: add get enterprise cluster endpoint

.github/workflows/ci.yaml, Dockerfile, docker/Dockerfile_template, docker/Dockerfile_template_mocked
=> feat: update Go version to 1.19.5

internal/kafka/internal/routes/route_loader.go, internal/kafka/test/integration/kafka/features/kafka-api.feature, internal/kafka/test/integration/metadata_test.go
add clusters in the returned /api/kafkas_mgmt/v1 collection response
1. `make run`
2. `curl -XGET -http://localhost:8000/api/kafkas_mgmt/v1/ | jq` and ensures that the clusters are returned as part of the collection
=> feat: add clusters in the returned /api/kafkas_mgmt/v1 collection response

internal/kafka/internal/api/dbapi/kafka_request_types.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/kafkas_mgr_test.go
Add logic to suspend expiring kafka instances.
A Kafka instance is suspended only if it is in one of the following statuses:
- KafkaRequestStatusAccepted
- KafkaRequestStatusPreparing
- KafkaRequestStatusReady
- KafkaRequestStatusProvisioning
- KafkaRequestStatusResuming,
Expired instances are ignored (we deal with them in #1471 )
1. Run KFM locally
2. Create a Kafka cluster. This can be simulated by adding the corresponding row into the database. If the reconcile for `active` state bother, disable it.
3. Update the Kafka request and set the ExpireAt column with a value sooner than your configured grace period
4. Verify that the cluster is moved to `suspending`
=> feat: add logic to suspend expiring instances

internal/kafka/internal/services/kafka.go
=> chore: remove duplicated log line during expiration evaluation time

cmd/kas-fleet-manager/main_test.go, config/quota-management-list-configuration.yaml, internal/kafka/internal/api/dbapi/kafka_request_types.go, internal/kafka/internal/migrations/20221219154830_add_kafka_promote_worker_in_leader_leases.go, internal/kafka/internal/migrations/migrations.go, internal/kafka/internal/services/kafka.go, internal/kafka/internal/services/kafkaservice_moq.go, internal/kafka/internal/services/quota.go, internal/kafka/internal/services/quota/ams_quota_service.go, internal/kafka/internal/services/quota/ams_quota_service_test.go, internal/kafka/internal/services/quota/internal/mocks/ams/reserved_resources_mock.go, internal/kafka/internal/services/quota/internal/mocks/ams/subscriptions_mock.go, internal/kafka/internal/services/quota/internal/utils/simple_billing_model_resolver.go, internal/kafka/internal/services/quota/quota_management_list_service.go, internal/kafka/internal/services/quotaservice_moq.go, internal/kafka/internal/workers/kafka_mgrs/promotion/chain/reconciler_chain.go, internal/kafka/internal/workers/kafka_mgrs/promotion/internal/actions/delete_actual_quota_action.go, internal/kafka/internal/workers/kafka_mgrs/promotion/internal/actions/promotion_context.go, internal/kafka/internal/workers/kafka_mgrs/promotion/internal/actions/reserve_desired_quota_action.go, internal/kafka/internal/workers/kafka_mgrs/promotion/internal/actions/update_kafka_request_action.go, internal/kafka/internal/workers/kafka_mgrs/promotion/promotion_kafkas_mgr.go, internal/kafka/internal/workers/kafka_mgrs/promotion/promotion_kafkas_mgr_test.go, internal/kafka/providers.go, internal/kafka/test/integration/kafka_promote_test.go, pkg/client/ocm/client.go, pkg/client/ocm/client_moq.go, pkg/errors/errors.go, pkg/errors/errors_test.go, pkg/quota_management/shared.go
This PR adds the promotion reconcile.
A kafka is chosen for promotion when all of the following conditions are verified:
- `ActualBillingModel` is not empty
- `DesiredBillingModel` is different than `ActualBillingModel`
=> Add reconciler for kafkas promotions

internal/kafka/internal/clusters/ocm_provider.go, internal/kafka/internal/clusters/types/types.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go
=> fix: correct typo in ClusterNodeTaint type

internal/kafka/internal/migrations/20230125110000_add_kafka_promote_worker_in_leader_leases.go, internal/kafka/internal/migrations/20230125120000_update_expires_at_zero_value.go, internal/kafka/internal/migrations/migrations.go
To reflect the order the migrations are executed in comparison to other migrations already applied
Migrations are applied correctly
=> refactor: reorder long-lived instances db migrations

internal/kafka/internal/api/private/api/openapi.yaml, internal/kafka/internal/api/private/api_observatorium_proxy.go, openapi/kas-fleet-manager-private.yaml
feat: add description to observatorium proxy endpoint to clarify the purpose of this endpoint
- ~~[ ] All PR comments are resolved either by addressing them or creating follow up tasks~~
=> feat: add description to obs proxy endpoint

internal/kafka/internal/services/kafka.go
remove duplicate imports of some package
Code review is enough and test should pass
=> refactor(kafka service): remove duplicate imports of some package

internal/kafka/internal/services/kafka_test.go
Remove unneeded kafka service from PrepareKafkaRequest method tests
Code review and test passing is enough
=> refactor(kafka-service-test): remove unneeded kafka service from PrepareKafkaRequest method tests

go.mod, go.sum, internal/kafka/test/integration/auth_test.go, internal/kafka/test/integration/kafka_list_search_order_test.go, internal/kafka/test/integration/kafkas_test.go, internal/kafka/test/integration/serviceaccounts_test.go, test/helper.go
The faker library originally located in https://github.com/bxcodec/faker has been archived and migrated to https://github.com/go-faker/faker. This set of changes change the code to use the new library location and upgrade the version from v3 to v4
Tests pass
=> feat: update and migrate faker library

.github/workflows/ci.yaml, scripts/local_db_setup.sh, templates/README.md, templates/db-template.yml
feat: align postgres version so that its consistent across all deployments (that will soon be using 12.13 version of postgres)
CI passes
`make db/teardown && make db/setup` creates database locally without any errors
=> feat: align postgres version so that its consistent across all deployments

docker/Dockerfile_template, docker/Dockerfile_template_mocked
feat: change postgres version in test dockerfiles
=> feat: change postgres version in test dockerfiles

Makefile
Updates the `gotestsum` dependency that we use to run tests from v1.8.2 to v1.9.0
Tests pass
=> feat: update gotestsum to v1.9.0

config/quota-management-list-configuration.yaml, pkg/quota_management/account_test.go, pkg/quota_management/billing_model.go, pkg/quota_management/quota.go, pkg/quota_management/quota_management_list_config_test.go
There was a custom grace period configuration in the quota list configuration.
That was in contrast with the configuration in the InstanceType.
=> fix(quota-list): remove grace period from quota list configuration

config/quota-management-list-configuration.yaml, internal/kafka/test/integration/kafka_promote_test.go
Nightly were failing because the reconciler was running every 30 seconds while the test timeout was 15 seconds.
=> fix: change the reconciler interval to 1 second for promotion tests

pr_check.sh
New secrets contain the '/' char, causing sed to fail.
=> fix: replace sed separator with '#'

internal/connector/internal/api/admin/private/api/openapi.yaml, internal/connector/internal/api/admin/private/api_connector_clusters_admin.go, internal/connector/internal/handlers/connector_admin.go, internal/connector/internal/handlers/connector_agent.go, internal/connector/internal/services/connector_cluster.go, internal/connector/test/integration/feature_test.go, internal/connector/test/integration/features/connector-agent-api.feature, openapi/connector_mgmt-private-admin.yaml
Implements https://issues.redhat.com/browse/MGDCTRS-1993
1. `make test/integration/connector `
=> connectors: MGDCTRS-1993: make deployment searchable for operator upgrade available

internal/kafka/internal/handlers/validation.go, internal/kafka/test/integration/kafka_create_test.go
relax the billing model validation when creating an enterprise Kafka. In case the billing model is not specified but the cluster_id is specified then we default to enterprie billing model
The integration test should pass
=> fix(enterprise): default to "enterprise" billing model when creating a cluster on dedicated cluster

internal/kafka/test/common/kafka_pollers.go, internal/kafka/test/integration/kafkas_test.go
Add database dump (kafka_requests) to integration test
=> feat: add database dump to integration tests

internal/kafka/test/integration/kafkas_test.go
=> fix: fix nightly test failing (quota list)

internal/kafka/test/integration/kafkas_test.go
seed the TestKafka_KafkaExpiration integration test with a dummy data plane cluster
No need for to acquire a running cluster, a dummy cluster is enough
=> refactor(test): seed the TestKafka_KafkaExpiration integration test with a dummy data plane cluster

internal/kafka/internal/services/kafka.go
Clarify error log when getting Route53 change batch request.
The previous error doesn't accurately describe what it failed to perform.
=> feat: clarify error log when getting Route53 change batch request

internal/connector/internal/handlers/connector_admin.go, internal/connector/internal/routes/route_loader.go, internal/connector/test/integration/feature_test.go, internal/connector/test/integration/features/connector-agent-api.feature, internal/connector/test/integration/features/connector-multitenancy-api.feature
Implements https://issues.redhat.com/browse/MGDCTRS-1994
1. ` make test/integration/connector`
=> MGDCTRS-1994: control plane: make deployment patch accept operatorId patching.

Makefile, README.md, docs/best-practices/testing.md, docs/getting-credentials-and-accounts.md, docs/interacting-with-fleet-manager.md, docs/observability/README.md, docs/populating-configuration.md, docs/quota-management-list-configuration.md, docs/slos/README.md, docs/testing.md
Several changes to the documentation.
Simplify the main README documentation. The main README had grown too much losing part of its usefulness. The idea is that the main README provides the most useful information first and links to other relevant documents where more detail is provided in case the user is interested.
Some additional documents have been created, being of special relevance the populating configuration document and the interacting with fleet manager document.
=> feat: reorganize README documentation and expand documentation

docs/feature-flags.md, docs/populating-configuration.md, pkg/services/sentry/config.go
=> feat: mention that GlitchTip is also supported as a Sentry service

.github/workflows/ci.yaml, Dockerfile, docker/Dockerfile_template, docker/Dockerfile_template_mocked
Includes bugfixes and security fixes
Tests pass
=> feat: update Go version to 1.19.6

templates/envoy-config-configmap.yml, templates/service-template.yml
The changelog are available at:
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.21/v1.21.0
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.22/v1.22.0
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.23/v1.23.0
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.24/v1.24.0
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.25/v1.25.0
NOTE: Please go through them and point out anything that we need to look at as far as our usage of envoy is concerned.
1. `make deploy/project` 
2. Deploy limitador and verify that rate limiting works.
To deploy limitador, follow the steps https://github.com/Kuadrant/limitador/tree/main/limitador-server/kubernetes#k8s-deployment 
The following are to be noted:
- Update the content of …
=> chore: update envoy base image

internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr_test.go
OpenShift 4.12 returns error creating secret `observability-proxy-credentials` due to missing `kind` property. Fixes #1592
1. Install using kas-installer using version 4.12 OSD and `main` branch. The installer will be stuck waiting for the creation of the fleetshard managed-agent. Checking the KFM logs, the error listed in #1592 will be seen.
2. Re-run kas-installer using the changes in this PR by placing the following configs in kas-installer.env:
```
KAS_FLEET_MANAGER_GIT_URL='git@github.com:MikeEdgar/kas-fleet-manager.git'
KAS_FLEET_MANAGER_GIT_REF='add-secret-typemeta'
KAS_FLEET_MANAGER_IMAGE_BUILD='true'
KAS_FLEET_MANAGER_IMAGE_REPOSITORY="${USER}/kas-fleet-manager"
KAS_FLEET_MANAGER_IMAGE_TAG='latest'
```
3. Installation will complete successfully
=> fix: Add TypeMeta to observability-proxy-credentials secret

Makefile
Containers kept accumulating in the user's local system after execution of that Makefile target
Run `make docs/generate/mermaid`.
Make sure that after the execution there are no new running nor stopped mermaid containers
=> feat: update mermaid generation Makefile target to cleanup containers when finished

Makefile
When the swagger docs container is run it is already configured to be automatically deleted on stop
=> chore: remove unneeded docker rm in swaggerdocs teardown Make target

internal/kafka/internal/handlers/observatorium_proxy.go, internal/kafka/internal/handlers/observatorium_proxy_test.go
token check should not consider multiaz value of cluster
=> fix: token check should not consider multiaz value of cluster

internal/kafka/internal/clusters/ocm_provider.go, internal/kafka/internal/clusters/ocm_provider_test.go, internal/kafka/internal/clusters/provider.go, internal/kafka/internal/clusters/provider_moq.go, internal/kafka/internal/clusters/standalone_provider.go, internal/kafka/internal/handlers/cluster.go, internal/kafka/internal/handlers/cluster_test.go, internal/kafka/test/integration/cluster_deregistration_endpoint_test.go, internal/kafka/test/integration/cluster_metrics_test.go, internal/kafka/test/integration/cluster_registration_endpoint_test.go, internal/kafka/test/integration/ocm_client_test.go, pkg/shared/utils/arrays/generic_array_utils.go, pkg/shared/utils/arrays/generic_array_utils_test.go, test/mocks/api_server.go
Validate that the organization owns the cluster that's being registered. Before this, any org admin could register the cluster even the ones that are not owned.
Closes https://issues.redhat.com/browse/MGDSTRM-10583
Added integration tests and unit test should pass
- ~~[ ] All PR comments are resolved either by addressing them or creating follow up tasks~~
=> feat(enterprise): validate that the organization owns the cluster that's being registered

internal/kafka/internal/converters/cluster.go, internal/kafka/test/helper.go, internal/kafka/test/mocks/clusters/clusters.go, internal/kafka/test/mocks/kafkas/kafkas.go
1. set default value for service account to avoid creating them when they are not needed when running integration tests. 
2. Plus other minor cleanups and improvements  in the test helper
Integration tests should pass
=> set default value for service account to avoid creating them when they are not needed when running integration tests. 

.github/CODEOWNERS
Use a GitHub group to notify connectors related code changes to the team members of the connectors team instead of having to specify individual people.
This allows us not having to add, ping and remember specific people from the connectors team, remembering their usernames and that group can also be updated dynamically when people/join the connectors team.
=> chore: update github CODEOWNERS to use cos-fleet-manager-reviewers group

internal/kafka/constants/constants.go
=> refactor: remove unused constant

.github/workflows/ci.yaml
See https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1625#issuecomment-1465873902
n/a
=> Increase timeout for PR#1625

.github/workflows/ci.yaml
This reverts commit 97c7b06c7a76fa79566cc9556b2cd9eb26eb4350 as the timeout increase was not needed.
=> Revert "Increase timeout for PR#1625"

Dockerfile, Makefile
This PR updates the main Dockerfile to make the download of the go's binary release multiplatform.
This allows bulding the main container image from different platforms where the base image of the Dockerfile is available.
The solution is compatible with both podman and docker.
The solution is based on the new BuildKit container image builder backend available in docker.
Note: I am aware there are other Dockerfiles that also download Go binary release. This PR is only concerned about the main container image.
Note: We will need to be on the look for potential issues on the midstream pipelines / other pipelines due to this functionality has been integrated relatively recently in docker so depending on the docker version being used on those places we might detect some issues.
building the …
=> feat: make Dockerfile's go binary release download multiplaform

.github/workflows/ci.yaml, pr_check.sh
=> ci(image): add PR check that ensures that image can be built

internal/kafka/internal/services/kafkatlscertmgmt/kafka_tls_certificate_management_service.go
disable ocp stapling if MustStaple configuration is set to false
=> feat(certs): disable ocp stapling if MustStaple configuration is set to false

Makefile, pkg/client/aws/client.go, pkg/client/aws/client_test.go, pkg/client/aws/route53_client.go, pkg/client/aws/route53_client_moq.go, pkg/client/keycloak/client.go, pkg/client/keycloak/client_test.go, pkg/client/keycloak/gocloak_client_interface.go, pkg/client/keycloak/gocloak_client_interface_moq.go
This allows us to move the mock autogeneration to our own code instead of generating them from the vendor directory through additional addon tasks.
* KAS Fleet Manager  binary compiles successfully
* Tests pass
=> refactor: internalize GoCloak and AWS Route53 interface clients

Dockerfile, Makefile
Use Go modules instead.
By using Go modules instead of vendoring:
* We avoid needing to generate the vendored dependencies explicitly
* We remove the need to pre-generate vendored dependencies to work with KFM code and its related tasks
* We do not need to keep a working copy of the vendored dependencies in the project's directory
* Fully move away from GOPATH specific behaviors
* Avoid having inconsistent dependencies: Inconsistent vendoring errors would happen from time to time due to go.mod/sum not matching the generated vendored dependencies.
Additionally, the changes made ensure that when building the main container image, image layer caching is still preserved when using Go modules.
First make sure that you remove your local `vendor` directory from the project.
* Tests pass
* KFM …
=> feat: remove Go vendoring

internal/kafka/internal/api/public/api/openapi.yaml, internal/kafka/internal/presenters/kafka.go, internal/kafka/internal/presenters/kafka_test.go, internal/kafka/test/integration/kafka_create_test.go, internal/kafka/test/integration/kafkas_test.go, openapi/kas-fleet-manager.yaml
feat: update browser_url value: https://issues.redhat.com/browse/MGDSTRM-10946
tests should pass
=> feat: update browser_url value

internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_down_mgr.go, internal/kafka/internal/workers/cluster_mgrs/dynamic_scale_down_mgr_test.go
While trying out the fleet manager locally, I observed that KFM attemps to scale down the enterprise cluster as can be observed from the logs.
```
I0322 16:21:16.036258 1 dynamic_scale_down_mgr.go:114] evaluating dynamic scale down for cluster "23ruvhn0o1sqspso2sce69g5ghbamjoo"
I0322 16:21:16.036275 1 dynamic_scale_down_mgr.go:315] skipping candidate cluster with cluster id "23ruvhn0o1sqspso2sce69g5ghbamjoo"
I0322 16:21:16.036284 1 dynamic_scale_down_mgr.go:121] data plane scale down need detected for cluster "23ruvhn0o1sqspso2sce69g5ghbamjoo"
I0322 16:21:16.036289 1 dynamic_scale_down_mgr.go:370] scale down running in dryRun mode. No action is taken for cluster with cluster id "23ruvhn0o1sqspso2sce69g5ghbamjoo".
```
`23ruvhn0o1sqspso2sce69g5ghbamjoo` is an enterprise cluster that I've in …
=> fix(dynamic_scale_down_mgr): do not attempt to scale down enterprise clusters

internal/kafka/internal/services/kafka.go, internal/kafka/internal/services/kafka_test.go
only update certificate information in the database if they've changed thus avoid calling/soliciting the database each time.
Added unit test should pass
- ~~[ ] All acceptance criteria specified in JIRA have been completed~~ 
=> refactor: only update certificate information in the database if they've changed

docs/populating-configuration.md
It also reorganizes the observability stack documentation in the populating configuration docs
=> doc: update populating configuration doc to include observabilit rw proxy

pkg/client/observatorium/client_test.go
=> fix: unused variable linter error on observatorium client test

internal/connector/internal/config/connectors.go
Fixes parsing of comma separated options using string slice pflag
CI tests should pass. 
=> fix(connectors): fix parsing of comma separated string slice command line options

internal/connector/internal/api/admin/private/api/openapi.yaml, internal/connector/internal/api/admin/private/model_list.go, internal/connector/internal/api/private/api/openapi.yaml, internal/connector/internal/api/private/model_list.go, internal/connector/internal/api/public/api/openapi.yaml, internal/connector/internal/api/public/model_list.go, internal/kafka/internal/api/public/api/openapi.yaml, openapi/connector_mgmt-private-admin.yaml, openapi/connector_mgmt-private.yaml, openapi/connector_mgmt.yaml, openapi/kas-fleet-manager.yaml
Following up on the work started here: #1518
And sneaking in a minor workaround that seems to not be affecting the generated code at all.
cc. @lburgazzoli
=> OpenAPI No inheritance in connector_mgmt spec

README.md, config/admin-authz-configuration.yaml, docs/admin-api-endpoints-authorization.md, docs/admin-api-overview.md
The current upstream documentation related to KFM Admin Endpoint was very sparse, which did not allow any user of KFM to understand how the KFM Admin endpoints work.
Aside from that, it contained details specific to how we configure it in Red Hat. The upstream repository of KFM and therefore its documentation should not contain any particularities of the KFM deployment(s) in Red Hat.
This PR rewrites and expands the Fleet Manager API endpoints documentation.
This will help users understand how the KFM admin endpoints work, how to configure them and how to interact with them.
=> docs: Rewrite and expand Fleet Manager API endpoints documentation

Makefile
Includes bugfixes and updated linters versions
* Tests pass*
* Running `make lint` locally finishes successfully
=> chore: update golangci-lint to v1.52.2

internal/kafka/internal/services/data_plane_cluster.go, internal/kafka/internal/services/data_plane_cluster_test.go, internal/kafka/internal/workers/cluster_mgrs/clusters_mgr.go, internal/kafka/test/mocks/kasfleetshardsync/kas-fleetshard-sync.go, pkg/api/cluster_types.go
The ClusterFull status is no longer used, we can remove it.
Code review should be enough
=> refactor(cluster): remove unused ClusterFull status
